// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_Mat_exit1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        src_rows,
        src_cols,
        dst_rows,
        dst_cols,
        dst_rows_out_din,
        dst_rows_out_full_n,
        dst_rows_out_write,
        dst_cols_out_din,
        dst_cols_out_full_n,
        dst_cols_out_write,
        src_mat_rows_out_din,
        src_mat_rows_out_full_n,
        src_mat_rows_out_write,
        src_mat_cols_out_din,
        src_mat_cols_out_full_n,
        src_mat_cols_out_write,
        dst_mat_rows_out_din,
        dst_mat_rows_out_full_n,
        dst_mat_rows_out_write,
        dst_mat_cols_out_din,
        dst_mat_cols_out_full_n,
        dst_mat_cols_out_write,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] src_rows;
input  [31:0] src_cols;
input  [31:0] dst_rows;
input  [31:0] dst_cols;
output  [31:0] dst_rows_out_din;
input   dst_rows_out_full_n;
output   dst_rows_out_write;
output  [31:0] dst_cols_out_din;
input   dst_cols_out_full_n;
output   dst_cols_out_write;
output  [31:0] src_mat_rows_out_din;
input   src_mat_rows_out_full_n;
output   src_mat_rows_out_write;
output  [31:0] src_mat_cols_out_din;
input   src_mat_cols_out_full_n;
output   src_mat_cols_out_write;
output  [31:0] dst_mat_rows_out_din;
input   dst_mat_rows_out_full_n;
output   dst_mat_rows_out_write;
output  [31:0] dst_mat_cols_out_din;
input   dst_mat_cols_out_full_n;
output   dst_mat_cols_out_write;
output  [11:0] ap_return_0;
output  [11:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg start_write;
reg dst_rows_out_write;
reg dst_cols_out_write;
reg src_mat_rows_out_write;
reg src_mat_cols_out_write;
reg dst_mat_rows_out_write;
reg dst_mat_cols_out_write;
reg[11:0] ap_return_0;
reg[11:0] ap_return_1;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    dst_rows_out_blk_n;
reg    dst_cols_out_blk_n;
reg    src_mat_rows_out_blk_n;
reg    src_mat_cols_out_blk_n;
reg    dst_mat_rows_out_blk_n;
reg    dst_mat_cols_out_blk_n;
reg    ap_block_state1;
wire   [11:0] trunc_ln85_fu_112_p1;
wire   [11:0] trunc_ln85_1_fu_116_p1;
reg   [11:0] ap_return_0_preg;
reg   [11:0] ap_return_1_preg;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 12'd0;
#0 ap_return_1_preg = 12'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 12'd0;
    end else begin
        if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= trunc_ln85_fu_112_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 12'd0;
    end else begin
        if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= trunc_ln85_1_fu_116_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = trunc_ln85_fu_112_p1;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = trunc_ln85_1_fu_116_p1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_out_blk_n = dst_cols_out_full_n;
    end else begin
        dst_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_out_write = 1'b1;
    end else begin
        dst_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_mat_cols_out_blk_n = dst_mat_cols_out_full_n;
    end else begin
        dst_mat_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_mat_cols_out_write = 1'b1;
    end else begin
        dst_mat_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_mat_rows_out_blk_n = dst_mat_rows_out_full_n;
    end else begin
        dst_mat_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_mat_rows_out_write = 1'b1;
    end else begin
        dst_mat_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_out_blk_n = dst_rows_out_full_n;
    end else begin
        dst_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_out_write = 1'b1;
    end else begin
        dst_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_cols_out_blk_n = src_mat_cols_out_full_n;
    end else begin
        src_mat_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_cols_out_write = 1'b1;
    end else begin
        src_mat_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_rows_out_blk_n = src_mat_rows_out_full_n;
    end else begin
        src_mat_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_rows_out_write = 1'b1;
    end else begin
        src_mat_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (dst_mat_cols_out_full_n == 1'b0) | (dst_mat_rows_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign dst_cols_out_din = dst_cols;

assign dst_mat_cols_out_din = dst_cols;

assign dst_mat_rows_out_din = dst_rows;

assign dst_rows_out_din = dst_rows;

assign src_mat_cols_out_din = src_cols;

assign src_mat_rows_out_din = src_rows;

assign start_out = real_start;

assign trunc_ln85_1_fu_116_p1 = src_cols[11:0];

assign trunc_ln85_fu_112_p1 = src_rows[11:0];

endmodule //Block_Mat_exit1_proc
