// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module resize (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_dout,
        p_src_rows_empty_n,
        p_src_rows_read,
        p_src_cols_dout,
        p_src_cols_empty_n,
        p_src_cols_read,
        p_src_data_V_dout,
        p_src_data_V_empty_n,
        p_src_data_V_read,
        p_dst_rows_dout,
        p_dst_rows_empty_n,
        p_dst_rows_read,
        p_dst_cols_dout,
        p_dst_cols_empty_n,
        p_dst_cols_read,
        p_dst_data_V_din,
        p_dst_data_V_full_n,
        p_dst_data_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_dout;
input   p_src_rows_empty_n;
output   p_src_rows_read;
input  [31:0] p_src_cols_dout;
input   p_src_cols_empty_n;
output   p_src_cols_read;
input  [23:0] p_src_data_V_dout;
input   p_src_data_V_empty_n;
output   p_src_data_V_read;
input  [31:0] p_dst_rows_dout;
input   p_dst_rows_empty_n;
output   p_dst_rows_read;
input  [31:0] p_dst_cols_dout;
input   p_dst_cols_empty_n;
output   p_dst_cols_read;
output  [23:0] p_dst_data_V_din;
input   p_dst_data_V_full_n;
output   p_dst_data_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_rows_read;
reg p_src_cols_read;
reg p_src_data_V_read;
reg p_dst_rows_read;
reg p_dst_cols_read;
reg p_dst_data_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_rows_blk_n;
reg    p_src_cols_blk_n;
reg    p_dst_rows_blk_n;
reg    p_dst_cols_blk_n;
reg   [31:0] p_src_rows_read_reg_66;
reg    ap_block_state1;
reg   [31:0] p_src_cols_read_reg_71;
reg   [31:0] p_dst_rows_read_reg_76;
reg   [31:0] p_dst_cols_read_reg_81;
wire    grp_resizeNNBilinear_fu_54_ap_start;
wire    grp_resizeNNBilinear_fu_54_ap_done;
wire    grp_resizeNNBilinear_fu_54_ap_idle;
wire    grp_resizeNNBilinear_fu_54_ap_ready;
wire    grp_resizeNNBilinear_fu_54_imgInput_data_V_read;
wire   [23:0] grp_resizeNNBilinear_fu_54_imgOutput_data_V_din;
wire    grp_resizeNNBilinear_fu_54_imgOutput_data_V_write;
reg    grp_resizeNNBilinear_fu_54_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_resizeNNBilinear_fu_54_ap_start_reg = 1'b0;
end

resizeNNBilinear grp_resizeNNBilinear_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_fu_54_ap_start),
    .ap_done(grp_resizeNNBilinear_fu_54_ap_done),
    .ap_idle(grp_resizeNNBilinear_fu_54_ap_idle),
    .ap_ready(grp_resizeNNBilinear_fu_54_ap_ready),
    .imgInput_rows_read(p_src_rows_read_reg_66),
    .imgInput_cols_read(p_src_cols_read_reg_71),
    .imgInput_data_V_dout(p_src_data_V_dout),
    .imgInput_data_V_empty_n(p_src_data_V_empty_n),
    .imgInput_data_V_read(grp_resizeNNBilinear_fu_54_imgInput_data_V_read),
    .imgOutput_rows_read(p_dst_rows_read_reg_76),
    .imgOutput_cols_read(p_dst_cols_read_reg_81),
    .imgOutput_data_V_din(grp_resizeNNBilinear_fu_54_imgOutput_data_V_din),
    .imgOutput_data_V_full_n(p_dst_data_V_full_n),
    .imgOutput_data_V_write(grp_resizeNNBilinear_fu_54_imgOutput_data_V_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_resizeNNBilinear_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_resizeNNBilinear_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_fu_54_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_dst_cols_read_reg_81 <= p_dst_cols_dout;
        p_dst_rows_read_reg_76 <= p_dst_rows_dout;
        p_src_cols_read_reg_71 <= p_src_cols_dout;
        p_src_rows_read_reg_66 <= p_src_rows_dout;
    end
end

always @ (*) begin
    if (((grp_resizeNNBilinear_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_resizeNNBilinear_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_dst_cols_blk_n = p_dst_cols_empty_n;
    end else begin
        p_dst_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_dst_cols_read = 1'b1;
    end else begin
        p_dst_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_dst_data_V_write = grp_resizeNNBilinear_fu_54_imgOutput_data_V_write;
    end else begin
        p_dst_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_dst_rows_blk_n = p_dst_rows_empty_n;
    end else begin
        p_dst_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_dst_rows_read = 1'b1;
    end else begin
        p_dst_rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_blk_n = p_src_cols_empty_n;
    end else begin
        p_src_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_read = 1'b1;
    end else begin
        p_src_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_src_data_V_read = grp_resizeNNBilinear_fu_54_imgInput_data_V_read;
    end else begin
        p_src_data_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_blk_n = p_src_rows_empty_n;
    end else begin
        p_src_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_read = 1'b1;
    end else begin
        p_src_rows_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_resizeNNBilinear_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (p_dst_cols_empty_n == 1'b0) | (p_dst_rows_empty_n == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_resizeNNBilinear_fu_54_ap_start = grp_resizeNNBilinear_fu_54_ap_start_reg;

assign p_dst_data_V_din = grp_resizeNNBilinear_fu_54_imgOutput_data_V_din;

endmodule //resize
