// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================
/* Optimization type */
#define RO 			0    // Resource Optimized (8-pixel implementation)
#define NO 			1	 // Normal Operation (1-pixel implementation)


#define RGBA 1
#define GRAY 0
/* Interpolation type*/
#define INTERPOLATION	1
// 0 - Nearest Neighbor Interpolation
// 1 - Bilinear Interpolation
// 2 - AREA Interpolation

/* Max image Dimensions */
#define WIDTH 			640	// Maximum  image width
#define HEIGHT 			360   	// Maximum image height


