// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module resizeNNBilinear (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgInput_rows_read,
        imgInput_cols_read,
        imgInput_data_V_dout,
        imgInput_data_V_empty_n,
        imgInput_data_V_read,
        imgOutput_rows_read,
        imgOutput_cols_read,
        imgOutput_data_V_din,
        imgOutput_data_V_full_n,
        imgOutput_data_V_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_pp0_stage0 = 12'd8;
parameter    ap_ST_fsm_state6 = 12'd16;
parameter    ap_ST_fsm_state7 = 12'd32;
parameter    ap_ST_fsm_state8 = 12'd64;
parameter    ap_ST_fsm_state9 = 12'd128;
parameter    ap_ST_fsm_state10 = 12'd256;
parameter    ap_ST_fsm_state11 = 12'd512;
parameter    ap_ST_fsm_pp1_stage0 = 12'd1024;
parameter    ap_ST_fsm_state23 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] imgInput_rows_read;
input  [31:0] imgInput_cols_read;
input  [23:0] imgInput_data_V_dout;
input   imgInput_data_V_empty_n;
output   imgInput_data_V_read;
input  [31:0] imgOutput_rows_read;
input  [31:0] imgOutput_cols_read;
output  [23:0] imgOutput_data_V_din;
input   imgOutput_data_V_full_n;
output   imgOutput_data_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgInput_data_V_read;
reg imgOutput_data_V_write;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    imgInput_data_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_flatten_reg_2119;
reg    ap_enable_reg_pp1_iter4;
wire    ap_block_pp1_stage0;
reg   [0:0] tmp_12_reg_2296;
reg   [0:0] tmp_12_reg_2296_pp1_iter3_reg;
reg   [0:0] tmp_4_reg_2221;
reg   [0:0] or_cond_26_reg_2325;
reg   [0:0] or_cond_26_reg_2325_pp1_iter3_reg;
reg    imgOutput_data_V_blk_n;
reg    ap_enable_reg_pp1_iter10;
reg   [0:0] tmp_10_reg_2230;
reg   [0:0] or_cond4_reg_2335;
reg   [0:0] or_cond4_reg_2335_pp1_iter9_reg;
reg   [33:0] indvar_flatten_reg_363;
reg   [1:0] read_rows_count_reg_374;
reg   [30:0] j_reg_385;
reg   [31:0] j3_reg_443;
reg   [31:0] j3_reg_443_pp1_iter1_reg;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state12_pp1_stage0_iter0;
wire    ap_block_state13_pp1_stage0_iter1;
wire    ap_block_state14_pp1_stage0_iter2;
wire    ap_block_state15_pp1_stage0_iter3;
reg    ap_predicate_op198_read_state16;
reg    ap_block_state16_pp1_stage0_iter4;
wire    ap_block_state17_pp1_stage0_iter5;
wire    ap_block_state18_pp1_stage0_iter6;
wire    ap_block_state19_pp1_stage0_iter7;
wire    ap_block_state20_pp1_stage0_iter8;
wire    ap_block_state21_pp1_stage0_iter9;
reg    ap_predicate_op408_write_state22;
reg    ap_block_state22_pp1_stage0_iter10;
reg    ap_block_pp1_stage0_11001;
reg   [31:0] j3_reg_443_pp1_iter2_reg;
reg   [31:0] j3_reg_443_pp1_iter3_reg;
reg   [31:0] j3_reg_443_pp1_iter4_reg;
wire   [31:0] grp_xfUDivResize_fu_515_ap_return;
reg   [31:0] reg_568;
wire    ap_CS_fsm_state2;
wire    grp_xfUDivResize_fu_515_ap_idle;
wire    grp_xfUDivResize_fu_515_ap_ready;
wire    grp_xfUDivResize_fu_515_ap_done;
wire    ap_CS_fsm_state3;
wire   [41:0] grp_scaleCompute_fu_532_ap_return;
reg  signed [41:0] reg_572;
wire    ap_CS_fsm_state10;
reg    ap_enable_reg_pp1_iter3;
reg   [0:0] tmp_12_reg_2296_pp1_iter2_reg;
wire   [23:0] line_buffer_2_0_V_q0;
reg    ap_enable_reg_pp1_iter6;
reg   [0:0] tmp_12_reg_2296_pp1_iter5_reg;
reg   [0:0] tmp_7_reg_2246;
reg   [0:0] tmp_2_reg_2264;
reg   [0:0] tmp_42_reg_2329;
reg   [0:0] tmp_42_reg_2329_pp1_iter5_reg;
wire   [23:0] line_buffer_2_0_V_q1;
wire   [23:0] line_buffer_0_0_V_q0;
wire   [23:0] line_buffer_0_0_V_q1;
wire   [23:0] line_buffer_1_0_V_q0;
wire   [23:0] line_buffer_1_0_V_q1;
wire   [59:0] xnew_fu_612_p3;
reg   [59:0] xnew_reg_2068;
wire   [15:0] tmp_fu_621_p1;
reg   [15:0] tmp_reg_2073;
wire   [59:0] ynew_fu_626_p3;
reg   [59:0] ynew_reg_2094;
wire   [15:0] tmp_15_fu_635_p1;
reg   [15:0] tmp_15_reg_2099;
wire   [31:0] scalex_V_fu_640_p2;
reg   [31:0] scalex_V_reg_2104;
wire   [31:0] scaley_V_fu_646_p2;
reg   [31:0] scaley_V_reg_2109;
wire   [33:0] bound_fu_659_p1;
reg   [33:0] bound_reg_2114;
wire   [0:0] exitcond_flatten_fu_672_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [33:0] indvar_flatten_next_fu_677_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] cond_mid2_fu_709_p3;
reg   [0:0] cond_mid2_reg_2128;
wire   [1:0] read_rows_count_mid2_fu_717_p3;
reg   [9:0] line_buffer_0_0_V_s_reg_2137;
reg   [9:0] line_buffer_1_0_V_s_reg_2142;
wire   [30:0] j_1_fu_731_p2;
wire   [31:0] loop_row_count_fu_741_p3;
reg   [31:0] loop_row_count_reg_2172;
wire    ap_CS_fsm_state6;
wire   [31:0] loop_col_count_fu_751_p3;
reg   [31:0] loop_col_count_reg_2177;
wire   [31:0] tmp_1_fu_757_p2;
reg   [31:0] tmp_1_reg_2182;
wire   [42:0] tmp_51_i_fu_772_p1;
reg   [42:0] tmp_51_i_reg_2187;
wire   [53:0] tmp_56_i_fu_784_p3;
reg   [53:0] tmp_56_i_reg_2193;
wire   [41:0] tmp_59_i_fu_798_p3;
reg   [41:0] tmp_59_i_reg_2198;
wire   [53:0] tmp_65_i_fu_814_p3;
reg   [53:0] tmp_65_i_reg_2203;
wire   [41:0] indexx_pre_V_1_i_fu_828_p3;
reg   [41:0] indexx_pre_V_1_i_reg_2208;
wire   [31:0] i_1_fu_851_p2;
reg   [31:0] i_1_reg_2216;
wire    ap_CS_fsm_state7;
wire   [0:0] tmp_4_fu_857_p2;
wire   [0:0] tmp_8_fu_846_p2;
wire   [0:0] tmp_10_fu_862_p2;
reg   [0:0] tmp_57_reg_2235;
wire   [0:0] tmp_57_i_fu_871_p2;
reg   [0:0] tmp_57_i_reg_2241;
wire   [0:0] tmp_7_fu_876_p2;
wire    ap_CS_fsm_state11;
wire   [31:0] op2_assign_fu_882_p2;
reg   [31:0] op2_assign_reg_2250;
wire   [31:0] op2_assign_1_fu_888_p2;
reg   [31:0] op2_assign_1_reg_2258;
wire   [0:0] tmp_2_fu_894_p2;
wire   [21:0] tmp_52_fu_904_p1;
reg   [21:0] tmp_52_reg_2268;
wire   [21:0] tmp_53_fu_908_p1;
reg   [21:0] tmp_53_reg_2273;
wire   [42:0] r_V_9_fu_911_p2;
reg   [42:0] r_V_9_reg_2278;
wire   [41:0] p_Val2_1_fu_933_p3;
reg   [41:0] p_Val2_1_reg_2284;
wire   [23:0] tmp_58_fu_940_p1;
reg   [23:0] tmp_58_reg_2291;
wire   [0:0] tmp_12_fu_944_p2;
reg   [0:0] tmp_12_reg_2296_pp1_iter1_reg;
reg   [0:0] tmp_12_reg_2296_pp1_iter4_reg;
wire   [31:0] j_2_fu_949_p2;
reg   [31:0] j_2_reg_2300;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] tmp_52_i_fu_959_p2;
reg   [0:0] tmp_52_i_reg_2305;
wire   [0:0] tmp_20_fu_965_p2;
reg   [0:0] tmp_20_reg_2310;
wire   [0:0] tmp_44_fu_970_p2;
reg   [0:0] tmp_44_reg_2315;
wire   [1:0] tmp_71_fu_1059_p1;
reg   [1:0] tmp_71_reg_2320;
reg   [1:0] tmp_71_reg_2320_pp1_iter2_reg;
reg   [1:0] tmp_71_reg_2320_pp1_iter3_reg;
reg   [1:0] tmp_71_reg_2320_pp1_iter4_reg;
reg   [1:0] tmp_71_reg_2320_pp1_iter5_reg;
wire   [0:0] or_cond_26_fu_1078_p2;
reg   [0:0] or_cond_26_reg_2325_pp1_iter2_reg;
wire   [0:0] tmp_42_fu_1087_p2;
reg   [0:0] tmp_42_reg_2329_pp1_iter2_reg;
reg   [0:0] tmp_42_reg_2329_pp1_iter3_reg;
reg   [0:0] tmp_42_reg_2329_pp1_iter4_reg;
reg   [0:0] tmp_42_reg_2329_pp1_iter6_reg;
wire   [0:0] or_cond4_fu_1108_p2;
reg   [0:0] or_cond4_reg_2335_pp1_iter2_reg;
reg   [0:0] or_cond4_reg_2335_pp1_iter3_reg;
reg   [0:0] or_cond4_reg_2335_pp1_iter4_reg;
reg   [0:0] or_cond4_reg_2335_pp1_iter5_reg;
reg   [0:0] or_cond4_reg_2335_pp1_iter6_reg;
reg   [0:0] or_cond4_reg_2335_pp1_iter7_reg;
reg   [0:0] or_cond4_reg_2335_pp1_iter8_reg;
reg   [0:0] tmp_76_reg_2339;
wire   [0:0] tmp_66_i_fu_1127_p2;
reg   [0:0] tmp_66_i_reg_2345;
wire   [16:0] r_V_fu_1198_p3;
reg   [16:0] r_V_reg_2350;
reg   [11:0] WeightX_0_V_reg_2358;
reg   [11:0] WeightX_0_V_reg_2358_pp1_iter5_reg;
reg   [11:0] WeightX_0_V_reg_2358_pp1_iter6_reg;
reg   [11:0] WeightX_0_V_reg_2358_pp1_iter7_reg;
wire   [9:0] line_buffer_2_0_V_1_gep_fu_307_p3;
wire   [9:0] line_buffer_0_0_V_1_gep_fu_328_p3;
wire   [9:0] line_buffer_1_0_V_1_gep_fu_342_p3;
reg   [11:0] WeightY_V_reg_2424;
wire   [7:0] tmp_81_fu_1348_p1;
reg   [7:0] tmp_81_reg_2430;
reg   [7:0] tmp_81_reg_2430_pp1_iter8_reg;
wire   [21:0] p_Val2_8_fu_1963_p2;
reg   [21:0] p_Val2_8_reg_2435;
wire   [8:0] lhs_V_6_fu_1370_p1;
reg   [8:0] lhs_V_6_reg_2440;
wire   [8:0] r_V_3_fu_1378_p2;
reg   [8:0] r_V_3_reg_2445;
wire   [8:0] rhs_V_4_fu_1388_p1;
reg   [8:0] rhs_V_4_reg_2450;
wire   [8:0] r_V_4_fu_1392_p2;
reg   [8:0] r_V_4_reg_2455;
wire  signed [20:0] grp_fu_1969_p3;
reg  signed [20:0] r_V_2_reg_2460;
reg    ap_enable_reg_pp1_iter7;
wire   [7:0] p_Result_i_i_i_i17_2_fu_1401_p4;
reg   [7:0] p_Result_i_i_i_i17_2_reg_2465;
reg   [7:0] p_Result_i_i_i_i17_2_reg_2465_pp1_iter8_reg;
wire   [8:0] lhs_V_6_1_fu_1441_p1;
reg   [8:0] lhs_V_6_1_reg_2470;
wire   [8:0] r_V_3_1_fu_1449_p2;
reg   [8:0] r_V_3_1_reg_2475;
wire   [8:0] rhs_V_4_1_fu_1459_p1;
reg   [8:0] rhs_V_4_1_reg_2480;
wire   [8:0] r_V_4_1_fu_1463_p2;
reg   [8:0] r_V_4_1_reg_2485;
wire  signed [20:0] grp_fu_1977_p3;
reg  signed [20:0] r_V_12_1_reg_2490;
wire   [7:0] p_Result_i_i_i_i17_4_fu_1469_p4;
reg   [7:0] p_Result_i_i_i_i17_4_reg_2495;
reg   [7:0] p_Result_i_i_i_i17_4_reg_2495_pp1_iter8_reg;
wire   [8:0] lhs_V_6_2_fu_1509_p1;
reg   [8:0] lhs_V_6_2_reg_2500;
wire   [8:0] r_V_3_2_fu_1517_p2;
reg   [8:0] r_V_3_2_reg_2505;
wire   [8:0] rhs_V_4_2_fu_1527_p1;
reg   [8:0] rhs_V_4_2_reg_2510;
wire   [8:0] r_V_4_2_fu_1531_p2;
reg   [8:0] r_V_4_2_reg_2515;
wire  signed [20:0] grp_fu_1985_p3;
reg  signed [20:0] r_V_12_2_reg_2520;
wire  signed [22:0] grp_fu_1993_p4;
reg  signed [22:0] p_Val2_2_reg_2525;
reg    ap_enable_reg_pp1_iter8;
wire  signed [22:0] grp_fu_2012_p4;
reg  signed [22:0] p_Val2_2_1_reg_2530;
wire  signed [22:0] grp_fu_2031_p4;
reg  signed [22:0] p_Val2_2_2_reg_2535;
wire   [7:0] tmp_60_fu_1661_p3;
reg   [7:0] tmp_60_reg_2540;
wire   [7:0] tmp_66_fu_1741_p3;
reg   [7:0] tmp_66_reg_2545;
wire   [7:0] tmp_72_fu_1821_p3;
reg   [7:0] tmp_72_reg_2550;
wire   [31:0] output_rows_count_1_fu_1882_p3;
wire    ap_CS_fsm_state23;
wire   [31:0] read_rows_count_3_fu_1934_p3;
wire   [31:0] first_row_index_1_fu_1955_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state12;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter9;
reg   [9:0] line_buffer_0_0_V_address0;
reg    line_buffer_0_0_V_ce0;
reg    line_buffer_0_0_V_we0;
reg   [23:0] line_buffer_0_0_V_d0;
reg   [9:0] line_buffer_0_0_V_address1;
reg    line_buffer_0_0_V_ce1;
reg   [9:0] line_buffer_1_0_V_address0;
reg    line_buffer_1_0_V_ce0;
reg    line_buffer_1_0_V_we0;
reg   [23:0] line_buffer_1_0_V_d0;
reg   [9:0] line_buffer_1_0_V_address1;
reg    line_buffer_1_0_V_ce1;
reg   [9:0] line_buffer_2_0_V_address0;
reg    line_buffer_2_0_V_ce0;
reg    line_buffer_2_0_V_we0;
reg   [9:0] line_buffer_2_0_V_address1;
reg    line_buffer_2_0_V_ce1;
wire    grp_xfUDivResize_fu_515_ap_start;
reg   [59:0] grp_xfUDivResize_fu_515_in_n;
reg   [15:0] grp_xfUDivResize_fu_515_in_d;
reg   [31:0] grp_scaleCompute_fu_532_currindex;
reg   [31:0] grp_scaleCompute_fu_532_inscale_V;
reg    grp_scaleCompute_fu_532_ap_ce;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] read_rows_count_1_reg_396;
reg   [31:0] output_rows_count_reg_408;
reg   [31:0] indexstores_reg_420;
reg   [31:0] i3_reg_432;
reg   [31:0] ap_phi_mux_j3_phi_fu_447_p4;
wire   [0:0] ap_phi_mux_flag_write_2_phi_fu_460_p6;
wire   [0:0] ap_phi_reg_pp1_iter0_flag_write_2_reg_455;
reg   [0:0] ap_phi_reg_pp1_iter1_flag_write_2_reg_455;
reg   [0:0] ap_phi_reg_pp1_iter2_flag_write_2_reg_455;
reg   [0:0] ap_phi_reg_pp1_iter3_flag_write_2_reg_455;
reg   [0:0] ap_phi_reg_pp1_iter4_flag_write_2_reg_455;
reg   [0:0] ap_phi_reg_pp1_iter5_flag_write_2_reg_455;
wire   [23:0] ap_phi_reg_pp1_iter0_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter1_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter2_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter3_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter4_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter5_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter6_P0Buf_0_V_3_reg_471;
reg   [23:0] ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471;
wire   [23:0] ap_phi_reg_pp1_iter0_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter1_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter2_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter3_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter4_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter5_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter6_P0Buf_V_1_1_reg_482;
reg   [23:0] ap_phi_reg_pp1_iter7_P0Buf_V_1_1_reg_482;
wire   [23:0] ap_phi_reg_pp1_iter0_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter1_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter2_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter3_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter4_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter5_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter6_P0Buf_V_0_1_reg_493;
reg   [23:0] ap_phi_reg_pp1_iter7_P0Buf_V_0_1_reg_493;
wire   [23:0] ap_phi_reg_pp1_iter0_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter1_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter2_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter3_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter4_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter5_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter6_P0Buf_1_V_3_reg_504;
reg   [23:0] ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504;
reg    grp_xfUDivResize_fu_515_ap_start_reg;
wire   [63:0] tmp_11_fu_725_p1;
wire   [63:0] tmp_26_fu_1243_p1;
wire   [63:0] tmp_37_fu_1261_p1;
wire   [63:0] tmp_40_fu_1267_p1;
wire   [63:0] tmp_34_fu_1281_p1;
wire   [63:0] tmp_39_fu_1287_p1;
wire   [63:0] tmp_28_fu_1301_p1;
wire   [63:0] tmp_31_fu_1307_p1;
reg    ap_block_pp1_stage0_01001;
reg   [23:0] read_pixel_V_1_fu_174;
reg   [16:0] indexy_V_fu_178;
wire   [16:0] p_Val2_s_fu_1051_p3;
reg   [16:0] nextYScale_V_fu_182;
wire   [16:0] nextYScale_V_1_fu_1004_p3;
wire  signed [41:0] grp_fu_554_p1;
wire   [32:0] tmp_32_fu_652_p3;
wire   [31:0] j_cast_fu_663_p1;
wire   [0:0] tmp_9_fu_667_p2;
wire   [1:0] i_fu_691_p2;
wire   [0:0] cond_fu_703_p2;
wire   [0:0] cond_mid1_fu_697_p2;
wire   [30:0] j_mid2_fu_683_p3;
wire   [0:0] tmp_5_fu_737_p2;
wire   [0:0] tmp_6_fu_747_p2;
wire   [24:0] p_cast_fu_762_p4;
wire   [31:0] p_Val2_9_fu_779_p2;
wire   [19:0] tmp_35_fu_776_p1;
wire   [19:0] tmp_45_fu_792_p2;
wire   [31:0] p_Val2_5_fu_809_p2;
wire   [19:0] tmp_46_fu_806_p1;
wire   [19:0] tmp_48_fu_822_p2;
wire  signed [41:0] tmp_53_i_fu_867_p0;
wire  signed [53:0] tmp_53_i_fu_867_p1;
wire  signed [42:0] tmp_i_fu_900_p1;
wire   [0:0] sel_tmp_i_fu_916_p2;
wire   [0:0] sel_tmp1_i_fu_921_p2;
wire   [41:0] sel_tmp2_i_fu_926_p3;
wire   [21:0] tmp_63_fu_955_p2;
wire   [16:0] tmp_14_fu_982_p4;
wire   [16:0] tmp_16_fu_991_p2;
wire   [0:0] tmp_59_fu_975_p3;
wire   [16:0] tmp_17_fu_997_p3;
wire   [21:0] tmp_69_fu_1019_p1;
wire   [16:0] tmp_19_fu_1028_p4;
wire   [0:0] tmp_60_i_fu_1022_p2;
wire   [16:0] tmp_23_fu_1037_p2;
wire   [0:0] tmp_65_fu_1012_p3;
wire   [16:0] tmp_25_fu_1043_p3;
wire   [31:0] tmp_18_fu_1063_p1;
wire   [0:0] slt_fu_1067_p2;
wire   [0:0] rev_fu_1072_p2;
wire   [31:0] tmp_41_fu_1083_p1;
wire   [0:0] brmerge_demorgan_fu_1092_p2;
wire   [0:0] tmp_43_fu_1097_p2;
wire   [0:0] or_cond3_fu_1102_p2;
wire  signed [41:0] tmp_62_i_fu_1123_p0;
wire  signed [53:0] tmp_62_i_fu_1123_p1;
wire   [0:0] sel_tmp5_i_fu_1132_p2;
wire   [0:0] sel_tmp6_i_fu_1137_p2;
wire   [41:0] sel_tmp7_i_fu_1142_p3;
wire   [41:0] p_Val2_i_fu_1149_p3;
wire   [21:0] tmp_78_fu_1164_p1;
wire   [16:0] tmp_49_fu_1174_p4;
wire   [0:0] tmp_68_i_fu_1168_p2;
wire   [16:0] tmp_50_fu_1184_p2;
wire   [0:0] tmp_77_fu_1156_p3;
wire   [16:0] tmp_51_fu_1190_p3;
wire   [1:0] tmp_79_fu_1206_p1;
wire   [23:0] tmp_80_fu_1218_p1;
wire   [23:0] p_Val2_4_i_fu_1210_p3;
wire   [23:0] p_Val2_8_i_fu_1222_p2;
wire   [17:0] tmp_42_cast_fu_1252_p1;
wire   [17:0] tmp_36_fu_1255_p2;
wire   [17:0] tmp_38_cast_fu_1272_p1;
wire   [17:0] tmp_33_fu_1275_p2;
wire   [17:0] tmp_31_cast_fu_1292_p1;
wire   [17:0] tmp_27_fu_1295_p2;
wire   [23:0] p_Val2_9_i_fu_1312_p3;
wire   [23:0] p_Val2_10_fu_1319_p2;
wire   [23:0] P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3;
wire   [23:0] P1Buf_V_1_1_P0Buf_V_s_fu_1334_p3;
wire   [7:0] tmp_84_fu_1360_p1;
wire   [8:0] rhs_V_fu_1374_p1;
wire   [7:0] tmp_82_fu_1352_p1;
wire   [7:0] tmp_83_fu_1356_p1;
wire   [8:0] lhs_V_3_fu_1384_p1;
wire   [7:0] p_Result_i_i_i_i_0_3_fu_1431_p4;
wire   [8:0] rhs_V_1_fu_1445_p1;
wire   [7:0] p_Result_i_i_i_i_0_2_fu_1411_p4;
wire   [7:0] p_Result_i_i_i_i17_3_fu_1421_p4;
wire   [8:0] lhs_V_3_1_fu_1455_p1;
wire   [7:0] p_Result_i_i_i_i_0_5_fu_1499_p4;
wire   [8:0] rhs_V_s_fu_1513_p1;
wire   [7:0] p_Result_i_i_i_i_0_4_fu_1479_p4;
wire   [7:0] p_Result_i_i_i_i17_5_fu_1489_p4;
wire   [8:0] lhs_V_3_2_fu_1523_p1;
wire   [11:0] Wxy_V_fu_1537_p4;
wire  signed [21:0] grp_fu_2003_p4;
wire  signed [21:0] grp_fu_2022_p4;
wire  signed [21:0] grp_fu_2041_p4;
wire   [17:0] p_Val2_s_27_fu_1589_p3;
wire  signed [23:0] tmp_90_cast_fu_1596_p1;
wire   [23:0] tmp_91_cast_fu_1599_p1;
wire   [23:0] p_Val2_3_fu_1611_p2;
wire   [9:0] tmp_86_fu_1607_p1;
wire   [9:0] tmp_85_fu_1603_p1;
wire   [9:0] tmp_88_fu_1625_p2;
wire   [7:0] tmp_54_fu_1637_p4;
wire   [0:0] tmp_47_fu_1631_p2;
wire   [7:0] tmp_55_fu_1647_p2;
wire   [0:0] tmp_87_fu_1617_p3;
wire   [7:0] tmp_56_fu_1653_p3;
wire   [17:0] p_Val2_13_1_fu_1669_p3;
wire  signed [23:0] tmp_90_1_cast_fu_1676_p1;
wire   [23:0] tmp_91_1_cast_fu_1679_p1;
wire   [23:0] p_Val2_14_1_fu_1691_p2;
wire   [9:0] tmp_90_fu_1687_p1;
wire   [9:0] tmp_89_fu_1683_p1;
wire   [9:0] tmp_92_fu_1705_p2;
wire   [7:0] tmp_61_fu_1717_p4;
wire   [0:0] tmp_96_1_fu_1711_p2;
wire   [7:0] tmp_62_fu_1727_p2;
wire   [0:0] tmp_91_fu_1697_p3;
wire   [7:0] tmp_64_fu_1733_p3;
wire   [17:0] p_Val2_13_2_fu_1749_p3;
wire  signed [23:0] tmp_90_2_cast_fu_1756_p1;
wire   [23:0] tmp_91_2_cast_fu_1759_p1;
wire   [23:0] p_Val2_14_2_fu_1771_p2;
wire   [9:0] tmp_94_fu_1767_p1;
wire   [9:0] tmp_93_fu_1763_p1;
wire   [9:0] tmp_96_fu_1785_p2;
wire   [7:0] tmp_67_fu_1797_p4;
wire   [0:0] tmp_96_2_fu_1791_p2;
wire   [7:0] tmp_68_fu_1807_p2;
wire   [0:0] tmp_95_fu_1777_p3;
wire   [7:0] tmp_70_fu_1813_p3;
wire   [31:0] tmp_21_fu_1843_p1;
wire   [0:0] tmp_22_fu_1847_p2;
wire   [0:0] or_cond1_fu_1852_p2;
wire   [0:0] tmp_24_fu_1857_p2;
wire   [0:0] or_cond2_fu_1862_p2;
wire   [31:0] output_rows_count_2_fu_1868_p2;
wire   [31:0] output_rows_count_2_s_fu_1874_p3;
wire   [31:0] tmp_29_fu_1889_p1;
wire   [31:0] first_row_index_fu_1898_p2;
wire   [31:0] read_rows_count_2_fu_1910_p2;
wire   [0:0] tmp_30_fu_1893_p2;
wire   [0:0] sel_tmp1_fu_1923_p2;
wire   [0:0] sel_tmp2_fu_1928_p2;
wire   [31:0] read_rows_count_4_fu_1916_p3;
wire   [0:0] tmp_38_fu_1904_p2;
wire   [0:0] or_cond_fu_1942_p2;
wire   [31:0] newSel_fu_1947_p3;
wire   [11:0] p_Val2_8_fu_1963_p0;
wire   [11:0] p_Val2_8_fu_1963_p1;
wire   [7:0] grp_fu_1969_p0;
wire   [7:0] grp_fu_1969_p1;
wire   [11:0] grp_fu_1969_p2;
wire   [20:0] OP2_V_3_cast_fu_1398_p1;
wire   [7:0] grp_fu_1977_p0;
wire   [7:0] grp_fu_1977_p1;
wire   [11:0] grp_fu_1977_p2;
wire   [7:0] grp_fu_1985_p0;
wire   [7:0] grp_fu_1985_p1;
wire   [11:0] grp_fu_1985_p2;
wire   [8:0] grp_fu_1993_p0;
wire   [8:0] grp_fu_1993_p1;
wire   [11:0] grp_fu_1993_p2;
wire   [21:0] OP2_V_2_cast_fu_1552_p1;
wire   [7:0] grp_fu_2003_p0;
wire   [7:0] grp_fu_2003_p1;
wire   [11:0] grp_fu_2003_p2;
wire   [20:0] OP2_V_4_cast_fu_1556_p1;
wire   [8:0] grp_fu_2012_p0;
wire   [8:0] grp_fu_2012_p1;
wire   [11:0] grp_fu_2012_p2;
wire   [7:0] grp_fu_2022_p0;
wire   [7:0] grp_fu_2022_p1;
wire   [11:0] grp_fu_2022_p2;
wire   [8:0] grp_fu_2031_p0;
wire   [8:0] grp_fu_2031_p1;
wire   [11:0] grp_fu_2031_p2;
wire   [7:0] grp_fu_2041_p0;
wire   [7:0] grp_fu_2041_p1;
wire   [11:0] grp_fu_2041_p2;
reg   [11:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [9:0] grp_fu_1993_p00;
wire   [9:0] grp_fu_1993_p10;
wire   [9:0] grp_fu_2012_p00;
wire   [9:0] grp_fu_2012_p10;
wire   [9:0] grp_fu_2031_p00;
wire   [9:0] grp_fu_2031_p10;
wire   [21:0] p_Val2_8_fu_1963_p00;
wire   [21:0] p_Val2_8_fu_1963_p10;
reg    ap_condition_631;
reg    ap_condition_653;
reg    ap_condition_78;
reg    ap_condition_198;
reg    ap_condition_191;
reg    ap_condition_1789;
reg    ap_condition_1793;
reg    ap_condition_412;
reg    ap_condition_423;
reg    ap_condition_1802;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 grp_xfUDivResize_fu_515_ap_start_reg = 1'b0;
end

resizeNNBilinear_dEe #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_0_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_0_0_V_address0),
    .ce0(line_buffer_0_0_V_ce0),
    .we0(line_buffer_0_0_V_we0),
    .d0(line_buffer_0_0_V_d0),
    .q0(line_buffer_0_0_V_q0),
    .address1(line_buffer_0_0_V_address1),
    .ce1(line_buffer_0_0_V_ce1),
    .q1(line_buffer_0_0_V_q1)
);

resizeNNBilinear_dEe #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_1_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_0_V_address0),
    .ce0(line_buffer_1_0_V_ce0),
    .we0(line_buffer_1_0_V_we0),
    .d0(line_buffer_1_0_V_d0),
    .q0(line_buffer_1_0_V_q0),
    .address1(line_buffer_1_0_V_address1),
    .ce1(line_buffer_1_0_V_ce1),
    .q1(line_buffer_1_0_V_q1)
);

resizeNNBilinear_dEe #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_2_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_2_0_V_address0),
    .ce0(line_buffer_2_0_V_ce0),
    .we0(line_buffer_2_0_V_we0),
    .d0(read_pixel_V_1_fu_174),
    .q0(line_buffer_2_0_V_q0),
    .address1(line_buffer_2_0_V_address1),
    .ce1(line_buffer_2_0_V_ce1),
    .q1(line_buffer_2_0_V_q1)
);

xfUDivResize grp_xfUDivResize_fu_515(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfUDivResize_fu_515_ap_start),
    .ap_done(grp_xfUDivResize_fu_515_ap_done),
    .ap_idle(grp_xfUDivResize_fu_515_ap_idle),
    .ap_ready(grp_xfUDivResize_fu_515_ap_ready),
    .in_n(grp_xfUDivResize_fu_515_in_n),
    .in_d(grp_xfUDivResize_fu_515_in_d),
    .ap_return(grp_xfUDivResize_fu_515_ap_return)
);

scaleCompute grp_scaleCompute_fu_532(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .currindex(grp_scaleCompute_fu_532_currindex),
    .inscale_V(grp_scaleCompute_fu_532_inscale_V),
    .ap_return(grp_scaleCompute_fu_532_ap_return),
    .ap_ce(grp_scaleCompute_fu_532_ap_ce)
);

resize_accel_mul_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
resize_accel_mul_g8j_U23(
    .din0(p_Val2_8_fu_1963_p0),
    .din1(p_Val2_8_fu_1963_p1),
    .dout(p_Val2_8_fu_1963_p2)
);

resize_accel_am_shbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
resize_accel_am_shbi_U24(
    .din0(grp_fu_1969_p0),
    .din1(grp_fu_1969_p1),
    .din2(grp_fu_1969_p2),
    .dout(grp_fu_1969_p3)
);

resize_accel_am_shbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
resize_accel_am_shbi_U25(
    .din0(grp_fu_1977_p0),
    .din1(grp_fu_1977_p1),
    .din2(grp_fu_1977_p2),
    .dout(grp_fu_1977_p3)
);

resize_accel_am_shbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
resize_accel_am_shbi_U26(
    .din0(grp_fu_1985_p0),
    .din1(grp_fu_1985_p1),
    .din2(grp_fu_1985_p2),
    .dout(grp_fu_1985_p3)
);

resize_accel_ama_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
resize_accel_ama_ibs_U27(
    .din0(grp_fu_1993_p0),
    .din1(grp_fu_1993_p1),
    .din2(grp_fu_1993_p2),
    .din3(grp_fu_2003_p4),
    .dout(grp_fu_1993_p4)
);

resize_accel_ama_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 21 ),
    .dout_WIDTH( 22 ))
resize_accel_ama_jbC_U28(
    .din0(grp_fu_2003_p0),
    .din1(grp_fu_2003_p1),
    .din2(grp_fu_2003_p2),
    .din3(r_V_2_reg_2460),
    .dout(grp_fu_2003_p4)
);

resize_accel_ama_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
resize_accel_ama_ibs_U29(
    .din0(grp_fu_2012_p0),
    .din1(grp_fu_2012_p1),
    .din2(grp_fu_2012_p2),
    .din3(grp_fu_2022_p4),
    .dout(grp_fu_2012_p4)
);

resize_accel_ama_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 21 ),
    .dout_WIDTH( 22 ))
resize_accel_ama_jbC_U30(
    .din0(grp_fu_2022_p0),
    .din1(grp_fu_2022_p1),
    .din2(grp_fu_2022_p2),
    .din3(r_V_12_1_reg_2490),
    .dout(grp_fu_2022_p4)
);

resize_accel_ama_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
resize_accel_ama_ibs_U31(
    .din0(grp_fu_2031_p0),
    .din1(grp_fu_2031_p1),
    .din2(grp_fu_2031_p2),
    .din3(grp_fu_2041_p4),
    .dout(grp_fu_2031_p4)
);

resize_accel_ama_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 21 ),
    .dout_WIDTH( 22 ))
resize_accel_ama_jbC_U32(
    .din0(grp_fu_2041_p0),
    .din1(grp_fu_2041_p1),
    .din2(grp_fu_2041_p2),
    .din3(r_V_12_2_reg_2520),
    .dout(grp_fu_2041_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state12) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state12)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state12);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp1_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfUDivResize_fu_515_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_xfUDivResize_fu_515_ap_done == 1'b1)))) begin
            grp_xfUDivResize_fu_515_ap_start_reg <= 1'b1;
        end else if ((grp_xfUDivResize_fu_515_ap_ready == 1'b1)) begin
            grp_xfUDivResize_fu_515_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_631)) begin
        if (((tmp_4_reg_2221 == 1'd1) & (tmp_12_reg_2296 == 1'd1))) begin
            ap_phi_reg_pp1_iter2_flag_write_2_reg_455 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter2_flag_write_2_reg_455 <= ap_phi_reg_pp1_iter1_flag_write_2_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        if ((1'b1 == ap_condition_653)) begin
            ap_phi_reg_pp1_iter3_flag_write_2_reg_455 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter3_flag_write_2_reg_455 <= ap_phi_reg_pp1_iter2_flag_write_2_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        if ((1'b1 == ap_condition_78)) begin
            ap_phi_reg_pp1_iter5_flag_write_2_reg_455 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter5_flag_write_2_reg_455 <= ap_phi_reg_pp1_iter4_flag_write_2_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        if ((1'b1 == ap_condition_191)) begin
            ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471 <= line_buffer_0_0_V_q0;
        end else if ((1'b1 == ap_condition_198)) begin
            ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471 <= line_buffer_2_0_V_q0;
        end else if (((tmp_7_reg_2246 == 1'd1) & (tmp_12_reg_2296_pp1_iter5_reg == 1'd1))) begin
            ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471 <= line_buffer_1_0_V_q0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter6_P0Buf_0_V_3_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        if ((1'b1 == ap_condition_191)) begin
            ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504 <= line_buffer_0_0_V_q1;
        end else if ((1'b1 == ap_condition_198)) begin
            ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504 <= line_buffer_2_0_V_q1;
        end else if (((tmp_7_reg_2246 == 1'd1) & (tmp_12_reg_2296_pp1_iter5_reg == 1'd1))) begin
            ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504 <= line_buffer_1_0_V_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter6_P0Buf_1_V_3_reg_504;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        if ((1'b1 == ap_condition_191)) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_0_1_reg_493 <= line_buffer_2_0_V_q0;
        end else if ((1'b1 == ap_condition_198)) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_0_1_reg_493 <= line_buffer_1_0_V_q0;
        end else if (((tmp_7_reg_2246 == 1'd1) & (tmp_12_reg_2296_pp1_iter5_reg == 1'd1))) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_0_1_reg_493 <= line_buffer_0_0_V_q0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter6_P0Buf_V_0_1_reg_493;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        if ((1'b1 == ap_condition_191)) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_1_1_reg_482 <= line_buffer_2_0_V_q1;
        end else if ((1'b1 == ap_condition_198)) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_1_1_reg_482 <= line_buffer_1_0_V_q1;
        end else if (((tmp_7_reg_2246 == 1'd1) & (tmp_12_reg_2296_pp1_iter5_reg == 1'd1))) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_1_1_reg_482 <= line_buffer_0_0_V_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter7_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter6_P0Buf_V_1_1_reg_482;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        i3_reg_432 <= i_1_reg_2216;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i3_reg_432 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        indexstores_reg_420 <= first_row_index_1_fu_1955_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indexstores_reg_420 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        indexy_V_fu_178 <= p_Val2_s_fu_1051_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indexy_V_fu_178 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_672_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_reg_363 <= indvar_flatten_next_fu_677_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
        indvar_flatten_reg_363 <= 34'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        j3_reg_443 <= j_2_reg_2300;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        j3_reg_443 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_672_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        j_reg_385 <= j_1_fu_731_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
        j_reg_385 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        nextYScale_V_fu_182 <= nextYScale_V_1_fu_1004_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        nextYScale_V_fu_182 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        output_rows_count_reg_408 <= output_rows_count_1_fu_1882_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_rows_count_reg_408 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        read_rows_count_1_reg_396 <= read_rows_count_3_fu_1934_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        read_rows_count_1_reg_396 <= 32'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_672_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        read_rows_count_reg_374 <= read_rows_count_mid2_fu_717_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
        read_rows_count_reg_374 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        WeightX_0_V_reg_2358 <= {{p_Val2_8_i_fu_1222_p2[23:12]}};
        r_V_reg_2350 <= r_V_fu_1198_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        WeightX_0_V_reg_2358_pp1_iter5_reg <= WeightX_0_V_reg_2358;
        WeightX_0_V_reg_2358_pp1_iter6_reg <= WeightX_0_V_reg_2358_pp1_iter5_reg;
        WeightX_0_V_reg_2358_pp1_iter7_reg <= WeightX_0_V_reg_2358_pp1_iter6_reg;
        j3_reg_443_pp1_iter2_reg <= j3_reg_443_pp1_iter1_reg;
        j3_reg_443_pp1_iter3_reg <= j3_reg_443_pp1_iter2_reg;
        j3_reg_443_pp1_iter4_reg <= j3_reg_443_pp1_iter3_reg;
        or_cond4_reg_2335_pp1_iter2_reg <= or_cond4_reg_2335;
        or_cond4_reg_2335_pp1_iter3_reg <= or_cond4_reg_2335_pp1_iter2_reg;
        or_cond4_reg_2335_pp1_iter4_reg <= or_cond4_reg_2335_pp1_iter3_reg;
        or_cond4_reg_2335_pp1_iter5_reg <= or_cond4_reg_2335_pp1_iter4_reg;
        or_cond4_reg_2335_pp1_iter6_reg <= or_cond4_reg_2335_pp1_iter5_reg;
        or_cond4_reg_2335_pp1_iter7_reg <= or_cond4_reg_2335_pp1_iter6_reg;
        or_cond4_reg_2335_pp1_iter8_reg <= or_cond4_reg_2335_pp1_iter7_reg;
        or_cond4_reg_2335_pp1_iter9_reg <= or_cond4_reg_2335_pp1_iter8_reg;
        or_cond_26_reg_2325_pp1_iter2_reg <= or_cond_26_reg_2325;
        or_cond_26_reg_2325_pp1_iter3_reg <= or_cond_26_reg_2325_pp1_iter2_reg;
        p_Result_i_i_i_i17_2_reg_2465_pp1_iter8_reg <= p_Result_i_i_i_i17_2_reg_2465;
        p_Result_i_i_i_i17_4_reg_2495_pp1_iter8_reg <= p_Result_i_i_i_i17_4_reg_2495;
        tmp_12_reg_2296_pp1_iter2_reg <= tmp_12_reg_2296_pp1_iter1_reg;
        tmp_12_reg_2296_pp1_iter3_reg <= tmp_12_reg_2296_pp1_iter2_reg;
        tmp_12_reg_2296_pp1_iter4_reg <= tmp_12_reg_2296_pp1_iter3_reg;
        tmp_12_reg_2296_pp1_iter5_reg <= tmp_12_reg_2296_pp1_iter4_reg;
        tmp_42_reg_2329_pp1_iter2_reg <= tmp_42_reg_2329;
        tmp_42_reg_2329_pp1_iter3_reg <= tmp_42_reg_2329_pp1_iter2_reg;
        tmp_42_reg_2329_pp1_iter4_reg <= tmp_42_reg_2329_pp1_iter3_reg;
        tmp_42_reg_2329_pp1_iter5_reg <= tmp_42_reg_2329_pp1_iter4_reg;
        tmp_42_reg_2329_pp1_iter6_reg <= tmp_42_reg_2329_pp1_iter5_reg;
        tmp_71_reg_2320_pp1_iter2_reg <= tmp_71_reg_2320;
        tmp_71_reg_2320_pp1_iter3_reg <= tmp_71_reg_2320_pp1_iter2_reg;
        tmp_71_reg_2320_pp1_iter4_reg <= tmp_71_reg_2320_pp1_iter3_reg;
        tmp_71_reg_2320_pp1_iter5_reg <= tmp_71_reg_2320_pp1_iter4_reg;
        tmp_81_reg_2430_pp1_iter8_reg <= tmp_81_reg_2430;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296_pp1_iter5_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        WeightY_V_reg_2424 <= {{p_Val2_10_fu_1319_p2[23:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_phi_reg_pp1_iter1_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter0_P0Buf_0_V_3_reg_471;
        ap_phi_reg_pp1_iter1_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter0_P0Buf_1_V_3_reg_504;
        ap_phi_reg_pp1_iter1_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter0_P0Buf_V_0_1_reg_493;
        ap_phi_reg_pp1_iter1_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter0_P0Buf_V_1_1_reg_482;
        ap_phi_reg_pp1_iter1_flag_write_2_reg_455 <= ap_phi_reg_pp1_iter0_flag_write_2_reg_455;
        j_2_reg_2300 <= j_2_fu_949_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_phi_reg_pp1_iter2_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter1_P0Buf_0_V_3_reg_471;
        ap_phi_reg_pp1_iter2_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter1_P0Buf_1_V_3_reg_504;
        ap_phi_reg_pp1_iter2_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter1_P0Buf_V_0_1_reg_493;
        ap_phi_reg_pp1_iter2_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter1_P0Buf_V_1_1_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_phi_reg_pp1_iter3_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter2_P0Buf_0_V_3_reg_471;
        ap_phi_reg_pp1_iter3_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter2_P0Buf_1_V_3_reg_504;
        ap_phi_reg_pp1_iter3_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter2_P0Buf_V_0_1_reg_493;
        ap_phi_reg_pp1_iter3_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter2_P0Buf_V_1_1_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_phi_reg_pp1_iter4_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter3_P0Buf_0_V_3_reg_471;
        ap_phi_reg_pp1_iter4_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter3_P0Buf_1_V_3_reg_504;
        ap_phi_reg_pp1_iter4_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter3_P0Buf_V_0_1_reg_493;
        ap_phi_reg_pp1_iter4_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter3_P0Buf_V_1_1_reg_482;
        ap_phi_reg_pp1_iter4_flag_write_2_reg_455 <= ap_phi_reg_pp1_iter3_flag_write_2_reg_455;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_phi_reg_pp1_iter5_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter4_P0Buf_0_V_3_reg_471;
        ap_phi_reg_pp1_iter5_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter4_P0Buf_1_V_3_reg_504;
        ap_phi_reg_pp1_iter5_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter4_P0Buf_V_0_1_reg_493;
        ap_phi_reg_pp1_iter5_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter4_P0Buf_V_1_1_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_phi_reg_pp1_iter6_P0Buf_0_V_3_reg_471 <= ap_phi_reg_pp1_iter5_P0Buf_0_V_3_reg_471;
        ap_phi_reg_pp1_iter6_P0Buf_1_V_3_reg_504 <= ap_phi_reg_pp1_iter5_P0Buf_1_V_3_reg_504;
        ap_phi_reg_pp1_iter6_P0Buf_V_0_1_reg_493 <= ap_phi_reg_pp1_iter5_P0Buf_V_0_1_reg_493;
        ap_phi_reg_pp1_iter6_P0Buf_V_1_1_reg_482 <= ap_phi_reg_pp1_iter5_P0Buf_V_1_1_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
        bound_reg_2114[32 : 1] <= bound_fu_659_p1[32 : 1];
        scalex_V_reg_2104[31 : 1] <= scalex_V_fu_640_p2[31 : 1];
        scaley_V_reg_2109[31 : 1] <= scaley_V_fu_646_p2[31 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_672_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cond_mid2_reg_2128 <= cond_mid2_fu_709_p3;
        line_buffer_0_0_V_s_reg_2137 <= tmp_11_fu_725_p1;
        line_buffer_1_0_V_s_reg_2142 <= tmp_11_fu_725_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_2119 <= exitcond_flatten_fu_672_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_1_reg_2216 <= i_1_fu_851_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        indexx_pre_V_1_i_reg_2208[41 : 22] <= indexx_pre_V_1_i_fu_828_p3[41 : 22];
        loop_col_count_reg_2177 <= loop_col_count_fu_751_p3;
        loop_row_count_reg_2172 <= loop_row_count_fu_741_p3;
        tmp_1_reg_2182 <= tmp_1_fu_757_p2;
        tmp_51_i_reg_2187[24 : 0] <= tmp_51_i_fu_772_p1[24 : 0];
        tmp_56_i_reg_2193[53 : 22] <= tmp_56_i_fu_784_p3[53 : 22];
        tmp_59_i_reg_2198[41 : 22] <= tmp_59_i_fu_798_p3[41 : 22];
        tmp_65_i_reg_2203[53 : 22] <= tmp_65_i_fu_814_p3[53 : 22];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        j3_reg_443_pp1_iter1_reg <= j3_reg_443;
        tmp_12_reg_2296 <= tmp_12_fu_944_p2;
        tmp_12_reg_2296_pp1_iter1_reg <= tmp_12_reg_2296;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond4_reg_2335_pp1_iter6_reg == 1'd1) & (tmp_10_reg_2230 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        lhs_V_6_1_reg_2470[7 : 0] <= lhs_V_6_1_fu_1441_p1[7 : 0];
        lhs_V_6_2_reg_2500[7 : 0] <= lhs_V_6_2_fu_1509_p1[7 : 0];
        lhs_V_6_reg_2440[7 : 0] <= lhs_V_6_fu_1370_p1[7 : 0];
        p_Result_i_i_i_i17_2_reg_2465 <= {{P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3[15:8]}};
        p_Result_i_i_i_i17_4_reg_2495 <= {{P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3[23:16]}};
        p_Val2_8_reg_2435 <= p_Val2_8_fu_1963_p2;
        r_V_3_1_reg_2475 <= r_V_3_1_fu_1449_p2;
        r_V_3_2_reg_2505 <= r_V_3_2_fu_1517_p2;
        r_V_3_reg_2445 <= r_V_3_fu_1378_p2;
        r_V_4_1_reg_2485 <= r_V_4_1_fu_1463_p2;
        r_V_4_2_reg_2515 <= r_V_4_2_fu_1531_p2;
        r_V_4_reg_2455 <= r_V_4_fu_1392_p2;
        rhs_V_4_1_reg_2480[7 : 0] <= rhs_V_4_1_fu_1459_p1[7 : 0];
        rhs_V_4_2_reg_2510[7 : 0] <= rhs_V_4_2_fu_1527_p1[7 : 0];
        rhs_V_4_reg_2450[7 : 0] <= rhs_V_4_fu_1388_p1[7 : 0];
        tmp_81_reg_2430 <= tmp_81_fu_1348_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        op2_assign_1_reg_2258 <= op2_assign_1_fu_888_p2;
        op2_assign_reg_2250 <= op2_assign_fu_882_p2;
        p_Val2_1_reg_2284 <= p_Val2_1_fu_933_p3;
        r_V_9_reg_2278 <= r_V_9_fu_911_p2;
        tmp_2_reg_2264 <= tmp_2_fu_894_p2;
        tmp_52_reg_2268 <= tmp_52_fu_904_p1;
        tmp_53_reg_2273 <= tmp_53_fu_908_p1;
        tmp_58_reg_2291 <= tmp_58_fu_940_p1;
        tmp_7_reg_2246 <= tmp_7_fu_876_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_10_reg_2230 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        or_cond4_reg_2335 <= or_cond4_fu_1108_p2;
        tmp_42_reg_2329 <= tmp_42_fu_1087_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296 == 1'd1) & (tmp_4_reg_2221 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        or_cond_26_reg_2325 <= or_cond_26_fu_1078_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond4_reg_2335_pp1_iter7_reg == 1'd1) & (tmp_10_reg_2230 == 1'd0) & (ap_enable_reg_pp1_iter8 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_Val2_2_1_reg_2530 <= grp_fu_2012_p4;
        p_Val2_2_2_reg_2535 <= grp_fu_2031_p4;
        p_Val2_2_reg_2525 <= grp_fu_1993_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond4_reg_2335_pp1_iter6_reg == 1'd1) & (tmp_10_reg_2230 == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        r_V_12_1_reg_2490 <= grp_fu_1977_p3;
        r_V_12_2_reg_2520 <= grp_fu_1985_p3;
        r_V_2_reg_2460 <= grp_fu_1969_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op198_read_state16 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        read_pixel_V_1_fu_174 <= imgInput_data_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_xfUDivResize_fu_515_ap_done == 1'b1)))) begin
        reg_568 <= grp_xfUDivResize_fu_515_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((tmp_12_reg_2296_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        reg_572 <= grp_scaleCompute_fu_532_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_8_fu_846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_10_reg_2230 <= tmp_10_fu_862_p2;
        tmp_4_reg_2221 <= tmp_4_fu_857_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
        tmp_15_reg_2099 <= tmp_15_fu_635_p1;
        ynew_reg_2094[59 : 28] <= ynew_fu_626_p3[59 : 28];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_fu_944_p2 == 1'd1) & (tmp_4_reg_2221 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_20_reg_2310 <= tmp_20_fu_965_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_fu_944_p2 == 1'd1) & (tmp_10_reg_2230 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_44_reg_2315 <= tmp_44_fu_970_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_fu_944_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_52_i_reg_2305 <= tmp_52_i_fu_959_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_57_i_reg_2241 <= tmp_57_i_fu_871_p2;
        tmp_57_reg_2235 <= grp_fu_554_p1[32'd41];
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond4_reg_2335_pp1_iter8_reg == 1'd1) & (tmp_10_reg_2230 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_60_reg_2540 <= tmp_60_fu_1661_p3;
        tmp_66_reg_2545 <= tmp_66_fu_1741_p3;
        tmp_72_reg_2550 <= tmp_72_fu_1821_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296_pp1_iter2_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_66_i_reg_2345 <= tmp_66_i_fu_1127_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_71_reg_2320 <= tmp_71_fu_1059_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_reg_2296_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_76_reg_2339 <= grp_fu_554_p1[32'd41];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_reg_2073 <= tmp_fu_621_p1;
        xnew_reg_2068[59 : 28] <= xnew_fu_612_p3[59 : 28];
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_672_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_12_fu_944_p2 == 1'd0)) begin
        ap_condition_pp1_exit_iter0_state12 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state12 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_8_fu_846_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_12_reg_2296 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_j3_phi_fu_447_p4 = j_2_reg_2300;
    end else begin
        ap_phi_mux_j3_phi_fu_447_p4 = j3_reg_443;
    end
end

always @ (*) begin
    if (((tmp_8_fu_846_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        grp_scaleCompute_fu_532_ap_ce = 1'b1;
    end else begin
        grp_scaleCompute_fu_532_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_12_fu_944_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_scaleCompute_fu_532_currindex = ap_phi_mux_j3_phi_fu_447_p4;
    end else if (((tmp_8_fu_846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        grp_scaleCompute_fu_532_currindex = output_rows_count_reg_408;
    end else begin
        grp_scaleCompute_fu_532_currindex = 'bx;
    end
end

always @ (*) begin
    if (((tmp_12_fu_944_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_scaleCompute_fu_532_inscale_V = scalex_V_reg_2104;
    end else if (((tmp_8_fu_846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        grp_scaleCompute_fu_532_inscale_V = scaley_V_reg_2109;
    end else begin
        grp_scaleCompute_fu_532_inscale_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_xfUDivResize_fu_515_in_d = tmp_15_reg_2099;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_xfUDivResize_fu_515_in_d = tmp_reg_2073;
    end else begin
        grp_xfUDivResize_fu_515_in_d = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_xfUDivResize_fu_515_in_n = ynew_reg_2094;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_xfUDivResize_fu_515_in_n = xnew_reg_2068;
    end else begin
        grp_xfUDivResize_fu_515_in_n = 'bx;
    end
end

always @ (*) begin
    if ((((or_cond_26_reg_2325_pp1_iter3_reg == 1'd1) & (tmp_12_reg_2296_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_4_reg_2221 == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((exitcond_flatten_reg_2119 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        imgInput_data_V_blk_n = imgInput_data_V_empty_n;
    end else begin
        imgInput_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op198_read_state16 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((exitcond_flatten_reg_2119 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        imgInput_data_V_read = 1'b1;
    end else begin
        imgInput_data_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond4_reg_2335_pp1_iter9_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_10_reg_2230 == 1'd0) & (ap_enable_reg_pp1_iter10 == 1'b1))) begin
        imgOutput_data_V_blk_n = imgOutput_data_V_full_n;
    end else begin
        imgOutput_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op408_write_state22 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        imgOutput_data_V_write = 1'b1;
    end else begin
        imgOutput_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_0_0_V_address0 = line_buffer_0_0_V_1_gep_fu_328_p3;
    end else if (((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_0_0_V_address0 = tmp_39_fu_1287_p1;
    end else if (((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_0_0_V_address0 = tmp_26_fu_1243_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_0_V_address0 = line_buffer_0_0_V_s_reg_2137;
    end else begin
        line_buffer_0_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1789)) begin
        if (((tmp_7_reg_2246 == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0))) begin
            line_buffer_0_0_V_address1 = tmp_28_fu_1301_p1;
        end else if (((tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0))) begin
            line_buffer_0_0_V_address1 = tmp_37_fu_1261_p1;
        end else begin
            line_buffer_0_0_V_address1 = 'bx;
        end
    end else begin
        line_buffer_0_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_0_0_V_ce0 = 1'b1;
    end else begin
        line_buffer_0_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_0_0_V_ce1 = 1'b1;
    end else begin
        line_buffer_0_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_0_0_V_d0 = read_pixel_V_1_fu_174;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_0_V_d0 = imgInput_data_V_dout;
    end else begin
        line_buffer_0_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cond_mid2_reg_2128 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_0_0_V_we0 = 1'b1;
    end else begin
        line_buffer_0_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_1_0_V_address0 = line_buffer_1_0_V_1_gep_fu_342_p3;
    end else if (((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_1_0_V_address0 = tmp_26_fu_1243_p1;
    end else if (((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_1_0_V_address0 = tmp_40_fu_1267_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_0_V_address0 = line_buffer_1_0_V_s_reg_2142;
    end else begin
        line_buffer_1_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1789)) begin
        if ((tmp_7_reg_2246 == 1'd1)) begin
            line_buffer_1_0_V_address1 = tmp_28_fu_1301_p1;
        end else if ((1'b1 == ap_condition_1793)) begin
            line_buffer_1_0_V_address1 = tmp_34_fu_1281_p1;
        end else begin
            line_buffer_1_0_V_address1 = 'bx;
        end
    end else begin
        line_buffer_1_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_1_0_V_ce0 = 1'b1;
    end else begin
        line_buffer_1_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_1_0_V_ce1 = 1'b1;
    end else begin
        line_buffer_1_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        line_buffer_1_0_V_d0 = read_pixel_V_1_fu_174;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_0_V_d0 = imgInput_data_V_dout;
    end else begin
        line_buffer_1_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cond_mid2_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_1_0_V_we0 = 1'b1;
    end else begin
        line_buffer_1_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        if (((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_7_reg_2246 == 1'd1))) begin
            line_buffer_2_0_V_address0 = tmp_31_fu_1307_p1;
        end else if ((1'b1 == ap_condition_423)) begin
            line_buffer_2_0_V_address0 = line_buffer_2_0_V_1_gep_fu_307_p3;
        end else if ((1'b1 == ap_condition_412)) begin
            line_buffer_2_0_V_address0 = tmp_26_fu_1243_p1;
        end else begin
            line_buffer_2_0_V_address0 = 'bx;
        end
    end else begin
        line_buffer_2_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1802)) begin
        if ((tmp_2_reg_2264 == 1'd1)) begin
            line_buffer_2_0_V_address1 = tmp_34_fu_1281_p1;
        end else if (((tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_2_reg_2264 == 1'd0))) begin
            line_buffer_2_0_V_address1 = tmp_37_fu_1261_p1;
        end else begin
            line_buffer_2_0_V_address1 = 'bx;
        end
    end else begin
        line_buffer_2_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_2_0_V_ce0 = 1'b1;
    end else begin
        line_buffer_2_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_2_0_V_ce1 = 1'b1;
    end else begin
        line_buffer_2_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_flag_write_2_phi_fu_460_p6 == 1'd1) & (tmp_7_reg_2246 == 1'd1) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_2_0_V_we0 = 1'b1;
    end else begin
        line_buffer_2_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_xfUDivResize_fu_515_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_flatten_fu_672_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_flatten_fu_672_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((tmp_8_fu_846_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((tmp_12_fu_944_p2 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((ap_enable_reg_pp1_iter9 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter10 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter9 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter10 == 1'b1)) | ((tmp_12_fu_944_p2 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP2_V_2_cast_fu_1552_p1 = Wxy_V_fu_1537_p4;

assign OP2_V_3_cast_fu_1398_p1 = WeightY_V_reg_2424;

assign OP2_V_4_cast_fu_1556_p1 = WeightX_0_V_reg_2358_pp1_iter7_reg;

assign P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3 = ((tmp_42_reg_2329_pp1_iter6_reg[0:0] === 1'b1) ? ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471 : ap_phi_reg_pp1_iter7_P0Buf_V_0_1_reg_493);

assign P1Buf_V_1_1_P0Buf_V_s_fu_1334_p3 = ((tmp_42_reg_2329_pp1_iter6_reg[0:0] === 1'b1) ? ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504 : ap_phi_reg_pp1_iter7_P0Buf_V_1_1_reg_482);

assign Wxy_V_fu_1537_p4 = {{p_Val2_8_reg_2435[21:10]}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond_flatten_reg_2119 == 1'd0) & (imgInput_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond_flatten_reg_2119 == 1'd0) & (imgInput_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((imgOutput_data_V_full_n == 1'b0) & (ap_predicate_op408_write_state22 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1)) | ((imgInput_data_V_empty_n == 1'b0) & (ap_predicate_op198_read_state16 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((imgOutput_data_V_full_n == 1'b0) & (ap_predicate_op408_write_state22 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1)) | ((imgInput_data_V_empty_n == 1'b0) & (ap_predicate_op198_read_state16 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((imgOutput_data_V_full_n == 1'b0) & (ap_predicate_op408_write_state22 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1)) | ((imgInput_data_V_empty_n == 1'b0) & (ap_predicate_op198_read_state16 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b1)));
end

assign ap_block_state12_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp1_stage0_iter4 = ((imgInput_data_V_empty_n == 1'b0) & (ap_predicate_op198_read_state16 == 1'b1));
end

assign ap_block_state17_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_pp1_stage0_iter10 = ((imgOutput_data_V_full_n == 1'b0) & (ap_predicate_op408_write_state22 == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((exitcond_flatten_reg_2119 == 1'd0) & (imgInput_data_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_1789 = ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1793 = ((tmp_2_reg_2264 == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_7_reg_2246 == 1'd0));
end

always @ (*) begin
    ap_condition_1802 = ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (tmp_7_reg_2246 == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_191 = ((tmp_12_reg_2296_pp1_iter5_reg == 1'd1) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0));
end

always @ (*) begin
    ap_condition_198 = ((tmp_2_reg_2264 == 1'd1) & (tmp_12_reg_2296_pp1_iter5_reg == 1'd1) & (tmp_7_reg_2246 == 1'd0));
end

always @ (*) begin
    ap_condition_412 = ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_42_reg_2329_pp1_iter4_reg == 1'd0) & (tmp_2_reg_2264 == 1'd0) & (tmp_7_reg_2246 == 1'd0));
end

always @ (*) begin
    ap_condition_423 = ((tmp_12_reg_2296_pp1_iter4_reg == 1'd1) & (tmp_2_reg_2264 == 1'd1) & (tmp_7_reg_2246 == 1'd0));
end

always @ (*) begin
    ap_condition_631 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001));
end

always @ (*) begin
    ap_condition_653 = ((tmp_12_reg_2296_pp1_iter1_reg == 1'd1) & (or_cond_26_reg_2325 == 1'd0) & (tmp_4_reg_2221 == 1'd0));
end

always @ (*) begin
    ap_condition_78 = ((or_cond_26_reg_2325_pp1_iter3_reg == 1'd1) & (tmp_12_reg_2296_pp1_iter3_reg == 1'd1) & (tmp_4_reg_2221 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_flag_write_2_phi_fu_460_p6 = ap_phi_reg_pp1_iter5_flag_write_2_reg_455;

assign ap_phi_reg_pp1_iter0_P0Buf_0_V_3_reg_471 = 'bx;

assign ap_phi_reg_pp1_iter0_P0Buf_1_V_3_reg_504 = 'bx;

assign ap_phi_reg_pp1_iter0_P0Buf_V_0_1_reg_493 = 'bx;

assign ap_phi_reg_pp1_iter0_P0Buf_V_1_1_reg_482 = 'bx;

assign ap_phi_reg_pp1_iter0_flag_write_2_reg_455 = 'bx;

always @ (*) begin
    ap_predicate_op198_read_state16 = ((or_cond_26_reg_2325_pp1_iter3_reg == 1'd1) & (tmp_12_reg_2296_pp1_iter3_reg == 1'd1) & (tmp_4_reg_2221 == 1'd0));
end

always @ (*) begin
    ap_predicate_op408_write_state22 = ((or_cond4_reg_2335_pp1_iter9_reg == 1'd1) & (tmp_10_reg_2230 == 1'd0));
end

assign bound_fu_659_p1 = tmp_32_fu_652_p3;

assign brmerge_demorgan_fu_1092_p2 = (tmp_4_reg_2221 & tmp_42_fu_1087_p2);

assign cond_fu_703_p2 = ((read_rows_count_reg_374 == 2'd0) ? 1'b1 : 1'b0);

assign cond_mid1_fu_697_p2 = ((i_fu_691_p2 == 2'd0) ? 1'b1 : 1'b0);

assign cond_mid2_fu_709_p3 = ((tmp_9_fu_667_p2[0:0] === 1'b1) ? cond_fu_703_p2 : cond_mid1_fu_697_p2);

assign exitcond_flatten_fu_672_p2 = ((indvar_flatten_reg_363 == bound_reg_2114) ? 1'b1 : 1'b0);

assign first_row_index_1_fu_1955_p3 = ((or_cond_fu_1942_p2[0:0] === 1'b1) ? indexstores_reg_420 : newSel_fu_1947_p3);

assign first_row_index_fu_1898_p2 = (indexstores_reg_420 + 32'd1);

assign grp_fu_1969_p0 = lhs_V_3_fu_1384_p1;

assign grp_fu_1969_p1 = lhs_V_6_fu_1370_p1;

assign grp_fu_1969_p2 = OP2_V_3_cast_fu_1398_p1;

assign grp_fu_1977_p0 = lhs_V_3_1_fu_1455_p1;

assign grp_fu_1977_p1 = lhs_V_6_1_fu_1441_p1;

assign grp_fu_1977_p2 = OP2_V_3_cast_fu_1398_p1;

assign grp_fu_1985_p0 = lhs_V_3_2_fu_1523_p1;

assign grp_fu_1985_p1 = lhs_V_6_2_fu_1509_p1;

assign grp_fu_1985_p2 = OP2_V_3_cast_fu_1398_p1;

assign grp_fu_1993_p0 = grp_fu_1993_p00;

assign grp_fu_1993_p00 = r_V_3_reg_2445;

assign grp_fu_1993_p1 = grp_fu_1993_p10;

assign grp_fu_1993_p10 = r_V_4_reg_2455;

assign grp_fu_1993_p2 = OP2_V_2_cast_fu_1552_p1;

assign grp_fu_2003_p0 = rhs_V_4_reg_2450;

assign grp_fu_2003_p1 = lhs_V_6_reg_2440;

assign grp_fu_2003_p2 = OP2_V_4_cast_fu_1556_p1;

assign grp_fu_2012_p0 = grp_fu_2012_p00;

assign grp_fu_2012_p00 = r_V_3_1_reg_2475;

assign grp_fu_2012_p1 = grp_fu_2012_p10;

assign grp_fu_2012_p10 = r_V_4_1_reg_2485;

assign grp_fu_2012_p2 = OP2_V_2_cast_fu_1552_p1;

assign grp_fu_2022_p0 = rhs_V_4_1_reg_2480;

assign grp_fu_2022_p1 = lhs_V_6_1_reg_2470;

assign grp_fu_2022_p2 = OP2_V_4_cast_fu_1556_p1;

assign grp_fu_2031_p0 = grp_fu_2031_p00;

assign grp_fu_2031_p00 = r_V_3_2_reg_2505;

assign grp_fu_2031_p1 = grp_fu_2031_p10;

assign grp_fu_2031_p10 = r_V_4_2_reg_2515;

assign grp_fu_2031_p2 = OP2_V_2_cast_fu_1552_p1;

assign grp_fu_2041_p0 = rhs_V_4_2_reg_2510;

assign grp_fu_2041_p1 = lhs_V_6_2_reg_2500;

assign grp_fu_2041_p2 = OP2_V_4_cast_fu_1556_p1;

assign grp_fu_554_p1 = grp_scaleCompute_fu_532_ap_return;

assign grp_xfUDivResize_fu_515_ap_start = grp_xfUDivResize_fu_515_ap_start_reg;

assign i_1_fu_851_p2 = (i3_reg_432 + 32'd1);

assign i_fu_691_p2 = (read_rows_count_reg_374 + 2'd1);

assign imgOutput_data_V_din = {{{tmp_72_reg_2550}, {tmp_66_reg_2545}}, {tmp_60_reg_2540}};

assign indexx_pre_V_1_i_fu_828_p3 = {{tmp_48_fu_822_p2}, {22'd0}};

assign indvar_flatten_next_fu_677_p2 = (indvar_flatten_reg_363 + 34'd1);

assign j_1_fu_731_p2 = (j_mid2_fu_683_p3 + 31'd1);

assign j_2_fu_949_p2 = (ap_phi_mux_j3_phi_fu_447_p4 + 32'd1);

assign j_cast_fu_663_p1 = j_reg_385;

assign j_mid2_fu_683_p3 = ((tmp_9_fu_667_p2[0:0] === 1'b1) ? j_reg_385 : 31'd0);

assign lhs_V_3_1_fu_1455_p1 = p_Result_i_i_i_i_0_2_fu_1411_p4;

assign lhs_V_3_2_fu_1523_p1 = p_Result_i_i_i_i_0_4_fu_1479_p4;

assign lhs_V_3_fu_1384_p1 = tmp_82_fu_1352_p1;

assign lhs_V_6_1_fu_1441_p1 = p_Result_i_i_i_i17_2_fu_1401_p4;

assign lhs_V_6_2_fu_1509_p1 = p_Result_i_i_i_i17_4_fu_1469_p4;

assign lhs_V_6_fu_1370_p1 = tmp_81_fu_1348_p1;

assign line_buffer_0_0_V_1_gep_fu_328_p3 = tmp_26_fu_1243_p1;

assign line_buffer_1_0_V_1_gep_fu_342_p3 = tmp_26_fu_1243_p1;

assign line_buffer_2_0_V_1_gep_fu_307_p3 = tmp_26_fu_1243_p1;

assign loop_col_count_fu_751_p3 = ((tmp_6_fu_747_p2[0:0] === 1'b1) ? imgOutput_cols_read : imgInput_cols_read);

assign loop_row_count_fu_741_p3 = ((tmp_5_fu_737_p2[0:0] === 1'b1) ? imgOutput_rows_read : imgInput_rows_read);

assign newSel_fu_1947_p3 = ((tmp_38_fu_1904_p2[0:0] === 1'b1) ? 32'd0 : first_row_index_fu_1898_p2);

assign nextYScale_V_1_fu_1004_p3 = ((tmp_59_fu_975_p3[0:0] === 1'b1) ? tmp_17_fu_997_p3 : tmp_14_fu_982_p4);

assign op2_assign_1_fu_888_p2 = ($signed(read_rows_count_1_reg_396) + $signed(32'd4294967294));

assign op2_assign_fu_882_p2 = ($signed(read_rows_count_1_reg_396) + $signed(32'd4294967295));

assign or_cond1_fu_1852_p2 = (tmp_4_reg_2221 & tmp_22_fu_1847_p2);

assign or_cond2_fu_1862_p2 = (tmp_24_fu_1857_p2 | or_cond1_fu_1852_p2);

assign or_cond3_fu_1102_p2 = (tmp_43_fu_1097_p2 | brmerge_demorgan_fu_1092_p2);

assign or_cond4_fu_1108_p2 = (tmp_44_reg_2315 & or_cond3_fu_1102_p2);

assign or_cond_26_fu_1078_p2 = (tmp_20_reg_2310 & rev_fu_1072_p2);

assign or_cond_fu_1942_p2 = (tmp_4_reg_2221 | sel_tmp2_fu_1928_p2);

assign output_rows_count_1_fu_1882_p3 = ((tmp_10_reg_2230[0:0] === 1'b1) ? output_rows_count_reg_408 : output_rows_count_2_s_fu_1874_p3);

assign output_rows_count_2_fu_1868_p2 = (output_rows_count_reg_408 + 32'd1);

assign output_rows_count_2_s_fu_1874_p3 = ((or_cond2_fu_1862_p2[0:0] === 1'b1) ? output_rows_count_2_fu_1868_p2 : output_rows_count_reg_408);

assign p_Result_i_i_i_i17_2_fu_1401_p4 = {{P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3[15:8]}};

assign p_Result_i_i_i_i17_3_fu_1421_p4 = {{P1Buf_V_1_1_P0Buf_V_s_fu_1334_p3[15:8]}};

assign p_Result_i_i_i_i17_4_fu_1469_p4 = {{P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3[23:16]}};

assign p_Result_i_i_i_i17_5_fu_1489_p4 = {{P1Buf_V_1_1_P0Buf_V_s_fu_1334_p3[23:16]}};

assign p_Result_i_i_i_i_0_2_fu_1411_p4 = {{ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471[15:8]}};

assign p_Result_i_i_i_i_0_3_fu_1431_p4 = {{ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504[15:8]}};

assign p_Result_i_i_i_i_0_4_fu_1479_p4 = {{ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471[23:16]}};

assign p_Result_i_i_i_i_0_5_fu_1499_p4 = {{ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504[23:16]}};

assign p_Val2_10_fu_1319_p2 = (tmp_58_reg_2291 - p_Val2_9_i_fu_1312_p3);

assign p_Val2_13_1_fu_1669_p3 = {{p_Result_i_i_i_i17_2_reg_2465_pp1_iter8_reg}, {10'd0}};

assign p_Val2_13_2_fu_1749_p3 = {{p_Result_i_i_i_i17_4_reg_2495_pp1_iter8_reg}, {10'd0}};

assign p_Val2_14_1_fu_1691_p2 = ($signed(tmp_90_1_cast_fu_1676_p1) + $signed(tmp_91_1_cast_fu_1679_p1));

assign p_Val2_14_2_fu_1771_p2 = ($signed(tmp_90_2_cast_fu_1756_p1) + $signed(tmp_91_2_cast_fu_1759_p1));

assign p_Val2_1_fu_933_p3 = ((tmp_57_reg_2235[0:0] === 1'b1) ? 42'd0 : sel_tmp2_i_fu_926_p3);

assign p_Val2_3_fu_1611_p2 = ($signed(tmp_90_cast_fu_1596_p1) + $signed(tmp_91_cast_fu_1599_p1));

assign p_Val2_4_i_fu_1210_p3 = {{tmp_79_fu_1206_p1}, {22'd0}};

assign p_Val2_5_fu_809_p2 = ($signed(32'd4294967295) + $signed(imgInput_cols_read));

assign p_Val2_8_fu_1963_p0 = p_Val2_8_fu_1963_p00;

assign p_Val2_8_fu_1963_p00 = WeightY_V_reg_2424;

assign p_Val2_8_fu_1963_p1 = p_Val2_8_fu_1963_p10;

assign p_Val2_8_fu_1963_p10 = WeightX_0_V_reg_2358_pp1_iter6_reg;

assign p_Val2_8_i_fu_1222_p2 = (tmp_80_fu_1218_p1 - p_Val2_4_i_fu_1210_p3);

assign p_Val2_9_fu_779_p2 = ($signed(32'd4294967295) + $signed(imgInput_rows_read));

assign p_Val2_9_i_fu_1312_p3 = {{tmp_71_reg_2320_pp1_iter5_reg}, {22'd0}};

assign p_Val2_i_fu_1149_p3 = ((tmp_76_reg_2339[0:0] === 1'b1) ? 42'd0 : sel_tmp7_i_fu_1142_p3);

assign p_Val2_s_27_fu_1589_p3 = {{tmp_81_reg_2430_pp1_iter8_reg}, {10'd0}};

assign p_Val2_s_fu_1051_p3 = ((tmp_65_fu_1012_p3[0:0] === 1'b1) ? tmp_25_fu_1043_p3 : tmp_19_fu_1028_p4);

assign p_cast_fu_762_p4 = {{reg_568[30:6]}};

assign r_V_3_1_fu_1449_p2 = (lhs_V_6_1_fu_1441_p1 + rhs_V_1_fu_1445_p1);

assign r_V_3_2_fu_1517_p2 = (lhs_V_6_2_fu_1509_p1 + rhs_V_s_fu_1513_p1);

assign r_V_3_fu_1378_p2 = (lhs_V_6_fu_1370_p1 + rhs_V_fu_1374_p1);

assign r_V_4_1_fu_1463_p2 = (lhs_V_3_1_fu_1455_p1 + rhs_V_4_1_fu_1459_p1);

assign r_V_4_2_fu_1531_p2 = (lhs_V_3_2_fu_1523_p1 + rhs_V_4_2_fu_1527_p1);

assign r_V_4_fu_1392_p2 = (lhs_V_3_fu_1384_p1 + rhs_V_4_fu_1388_p1);

assign r_V_9_fu_911_p2 = ($signed(tmp_i_fu_900_p1) + $signed(tmp_51_i_reg_2187));

assign r_V_fu_1198_p3 = ((tmp_77_fu_1156_p3[0:0] === 1'b1) ? tmp_51_fu_1190_p3 : tmp_49_fu_1174_p4);

assign read_rows_count_2_fu_1910_p2 = (read_rows_count_1_reg_396 + 32'd1);

assign read_rows_count_3_fu_1934_p3 = ((sel_tmp2_fu_1928_p2[0:0] === 1'b1) ? read_rows_count_1_reg_396 : read_rows_count_4_fu_1916_p3);

assign read_rows_count_4_fu_1916_p3 = ((tmp_4_reg_2221[0:0] === 1'b1) ? read_rows_count_1_reg_396 : read_rows_count_2_fu_1910_p2);

assign read_rows_count_mid2_fu_717_p3 = ((tmp_9_fu_667_p2[0:0] === 1'b1) ? read_rows_count_reg_374 : i_fu_691_p2);

assign rev_fu_1072_p2 = (slt_fu_1067_p2 ^ 1'd1);

assign rhs_V_1_fu_1445_p1 = p_Result_i_i_i_i_0_3_fu_1431_p4;

assign rhs_V_4_1_fu_1459_p1 = p_Result_i_i_i_i17_3_fu_1421_p4;

assign rhs_V_4_2_fu_1527_p1 = p_Result_i_i_i_i17_5_fu_1489_p4;

assign rhs_V_4_fu_1388_p1 = tmp_83_fu_1356_p1;

assign rhs_V_fu_1374_p1 = tmp_84_fu_1360_p1;

assign rhs_V_s_fu_1513_p1 = p_Result_i_i_i_i_0_5_fu_1499_p4;

assign scalex_V_fu_640_p2 = reg_568 << 32'd1;

assign scaley_V_fu_646_p2 = grp_xfUDivResize_fu_515_ap_return << 32'd1;

assign sel_tmp1_fu_1923_p2 = (tmp_4_reg_2221 ^ 1'd1);

assign sel_tmp1_i_fu_921_p2 = (tmp_57_i_reg_2241 & sel_tmp_i_fu_916_p2);

assign sel_tmp2_fu_1928_p2 = (tmp_30_fu_1893_p2 & sel_tmp1_fu_1923_p2);

assign sel_tmp2_i_fu_926_p3 = ((sel_tmp1_i_fu_921_p2[0:0] === 1'b1) ? tmp_59_i_reg_2198 : reg_572);

assign sel_tmp5_i_fu_1132_p2 = (tmp_76_reg_2339 ^ 1'd1);

assign sel_tmp6_i_fu_1137_p2 = (tmp_66_i_reg_2345 & sel_tmp5_i_fu_1132_p2);

assign sel_tmp7_i_fu_1142_p3 = ((sel_tmp6_i_fu_1137_p2[0:0] === 1'b1) ? indexx_pre_V_1_i_reg_2208 : reg_572);

assign sel_tmp_i_fu_916_p2 = (tmp_57_reg_2235 ^ 1'd1);

assign slt_fu_1067_p2 = (($signed(tmp_18_fu_1063_p1) < $signed(op2_assign_reg_2250)) ? 1'b1 : 1'b0);

assign tmp_10_fu_862_p2 = (($signed(output_rows_count_reg_408) > $signed(tmp_1_reg_2182)) ? 1'b1 : 1'b0);

assign tmp_11_fu_725_p1 = j_mid2_fu_683_p3;

assign tmp_12_fu_944_p2 = (($signed(ap_phi_mux_j3_phi_fu_447_p4) < $signed(loop_col_count_reg_2177)) ? 1'b1 : 1'b0);

assign tmp_14_fu_982_p4 = {{r_V_9_reg_2278[38:22]}};

assign tmp_15_fu_635_p1 = imgOutput_rows_read[15:0];

assign tmp_16_fu_991_p2 = (17'd1 + tmp_14_fu_982_p4);

assign tmp_17_fu_997_p3 = ((tmp_52_i_reg_2305[0:0] === 1'b1) ? tmp_14_fu_982_p4 : tmp_16_fu_991_p2);

assign tmp_18_fu_1063_p1 = nextYScale_V_1_fu_1004_p3;

assign tmp_19_fu_1028_p4 = {{p_Val2_1_reg_2284[38:22]}};

assign tmp_1_fu_757_p2 = ($signed(32'd4294967295) + $signed(imgOutput_rows_read));

assign tmp_20_fu_965_p2 = (($signed(ap_phi_mux_j3_phi_fu_447_p4) < $signed(imgInput_cols_read)) ? 1'b1 : 1'b0);

assign tmp_21_fu_1843_p1 = indexy_V_fu_178;

assign tmp_22_fu_1847_p2 = ((tmp_21_fu_1843_p1 == op2_assign_reg_2250) ? 1'b1 : 1'b0);

assign tmp_23_fu_1037_p2 = (17'd1 + tmp_19_fu_1028_p4);

assign tmp_24_fu_1857_p2 = ((tmp_21_fu_1843_p1 == op2_assign_1_reg_2258) ? 1'b1 : 1'b0);

assign tmp_25_fu_1043_p3 = ((tmp_60_i_fu_1022_p2[0:0] === 1'b1) ? tmp_19_fu_1028_p4 : tmp_23_fu_1037_p2);

assign tmp_26_fu_1243_p1 = r_V_reg_2350;

assign tmp_27_fu_1295_p2 = (tmp_31_cast_fu_1292_p1 + 18'd1);

assign tmp_28_fu_1301_p1 = tmp_27_fu_1295_p2;

assign tmp_29_fu_1889_p1 = nextYScale_V_fu_182;

assign tmp_2_fu_894_p2 = ((indexstores_reg_420 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_30_fu_1893_p2 = (($signed(tmp_29_fu_1889_p1) < $signed(op2_assign_reg_2250)) ? 1'b1 : 1'b0);

assign tmp_31_cast_fu_1292_p1 = r_V_reg_2350;

assign tmp_31_fu_1307_p1 = j3_reg_443_pp1_iter4_reg;

assign tmp_32_fu_652_p3 = {{imgInput_cols_read}, {1'd0}};

assign tmp_33_fu_1275_p2 = (tmp_38_cast_fu_1272_p1 + 18'd1);

assign tmp_34_fu_1281_p1 = tmp_33_fu_1275_p2;

assign tmp_35_fu_776_p1 = imgInput_rows_read[19:0];

assign tmp_36_fu_1255_p2 = (tmp_42_cast_fu_1252_p1 + 18'd1);

assign tmp_37_fu_1261_p1 = tmp_36_fu_1255_p2;

assign tmp_38_cast_fu_1272_p1 = r_V_reg_2350;

assign tmp_38_fu_1904_p2 = ((first_row_index_fu_1898_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_39_fu_1287_p1 = j3_reg_443_pp1_iter4_reg;

assign tmp_40_fu_1267_p1 = j3_reg_443_pp1_iter4_reg;

assign tmp_41_fu_1083_p1 = p_Val2_s_fu_1051_p3;

assign tmp_42_cast_fu_1252_p1 = r_V_reg_2350;

assign tmp_42_fu_1087_p2 = ((tmp_41_fu_1083_p1 == op2_assign_reg_2250) ? 1'b1 : 1'b0);

assign tmp_43_fu_1097_p2 = ((tmp_41_fu_1083_p1 == op2_assign_1_reg_2258) ? 1'b1 : 1'b0);

assign tmp_44_fu_970_p2 = (($signed(ap_phi_mux_j3_phi_fu_447_p4) < $signed(imgOutput_cols_read)) ? 1'b1 : 1'b0);

assign tmp_45_fu_792_p2 = ($signed(tmp_35_fu_776_p1) + $signed(20'd1048575));

assign tmp_46_fu_806_p1 = imgInput_cols_read[19:0];

assign tmp_47_fu_1631_p2 = ((tmp_88_fu_1625_p2 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_48_fu_822_p2 = ($signed(tmp_46_fu_806_p1) + $signed(20'd1048575));

assign tmp_49_fu_1174_p4 = {{p_Val2_i_fu_1149_p3[38:22]}};

assign tmp_4_fu_857_p2 = ((read_rows_count_1_reg_396 == imgInput_rows_read) ? 1'b1 : 1'b0);

assign tmp_50_fu_1184_p2 = (17'd1 + tmp_49_fu_1174_p4);

assign tmp_51_fu_1190_p3 = ((tmp_68_i_fu_1168_p2[0:0] === 1'b1) ? tmp_49_fu_1174_p4 : tmp_50_fu_1184_p2);

assign tmp_51_i_fu_772_p1 = p_cast_fu_762_p4;

assign tmp_52_fu_904_p1 = tmp_i_fu_900_p1[21:0];

assign tmp_52_i_fu_959_p2 = ((tmp_63_fu_955_p2 == 22'd0) ? 1'b1 : 1'b0);

assign tmp_53_fu_908_p1 = tmp_51_i_reg_2187[21:0];

assign tmp_53_i_fu_867_p0 = grp_scaleCompute_fu_532_ap_return;

assign tmp_53_i_fu_867_p1 = tmp_53_i_fu_867_p0;

assign tmp_54_fu_1637_p4 = {{p_Val2_3_fu_1611_p2[17:10]}};

assign tmp_55_fu_1647_p2 = (8'd1 + tmp_54_fu_1637_p4);

assign tmp_56_fu_1653_p3 = ((tmp_47_fu_1631_p2[0:0] === 1'b1) ? tmp_54_fu_1637_p4 : tmp_55_fu_1647_p2);

assign tmp_56_i_fu_784_p3 = {{p_Val2_9_fu_779_p2}, {22'd0}};

assign tmp_57_i_fu_871_p2 = (($signed(tmp_53_i_fu_867_p1) > $signed(tmp_56_i_reg_2193)) ? 1'b1 : 1'b0);

assign tmp_58_fu_940_p1 = p_Val2_1_fu_933_p3[23:0];

assign tmp_59_fu_975_p3 = r_V_9_reg_2278[32'd42];

assign tmp_59_i_fu_798_p3 = {{tmp_45_fu_792_p2}, {22'd0}};

assign tmp_5_fu_737_p2 = (($signed(imgOutput_rows_read) > $signed(imgInput_rows_read)) ? 1'b1 : 1'b0);

assign tmp_60_fu_1661_p3 = ((tmp_87_fu_1617_p3[0:0] === 1'b1) ? tmp_56_fu_1653_p3 : tmp_54_fu_1637_p4);

assign tmp_60_i_fu_1022_p2 = ((tmp_69_fu_1019_p1 == 22'd0) ? 1'b1 : 1'b0);

assign tmp_61_fu_1717_p4 = {{p_Val2_14_1_fu_1691_p2[17:10]}};

assign tmp_62_fu_1727_p2 = (8'd1 + tmp_61_fu_1717_p4);

assign tmp_62_i_fu_1123_p0 = grp_scaleCompute_fu_532_ap_return;

assign tmp_62_i_fu_1123_p1 = tmp_62_i_fu_1123_p0;

assign tmp_63_fu_955_p2 = (tmp_53_reg_2273 + tmp_52_reg_2268);

assign tmp_64_fu_1733_p3 = ((tmp_96_1_fu_1711_p2[0:0] === 1'b1) ? tmp_61_fu_1717_p4 : tmp_62_fu_1727_p2);

assign tmp_65_fu_1012_p3 = p_Val2_1_reg_2284[32'd41];

assign tmp_65_i_fu_814_p3 = {{p_Val2_5_fu_809_p2}, {22'd0}};

assign tmp_66_fu_1741_p3 = ((tmp_91_fu_1697_p3[0:0] === 1'b1) ? tmp_64_fu_1733_p3 : tmp_61_fu_1717_p4);

assign tmp_66_i_fu_1127_p2 = (($signed(tmp_62_i_fu_1123_p1) > $signed(tmp_65_i_reg_2203)) ? 1'b1 : 1'b0);

assign tmp_67_fu_1797_p4 = {{p_Val2_14_2_fu_1771_p2[17:10]}};

assign tmp_68_fu_1807_p2 = (8'd1 + tmp_67_fu_1797_p4);

assign tmp_68_i_fu_1168_p2 = ((tmp_78_fu_1164_p1 == 22'd0) ? 1'b1 : 1'b0);

assign tmp_69_fu_1019_p1 = p_Val2_1_reg_2284[21:0];

assign tmp_6_fu_747_p2 = (($signed(imgOutput_cols_read) > $signed(imgInput_cols_read)) ? 1'b1 : 1'b0);

assign tmp_70_fu_1813_p3 = ((tmp_96_2_fu_1791_p2[0:0] === 1'b1) ? tmp_67_fu_1797_p4 : tmp_68_fu_1807_p2);

assign tmp_71_fu_1059_p1 = p_Val2_s_fu_1051_p3[1:0];

assign tmp_72_fu_1821_p3 = ((tmp_95_fu_1777_p3[0:0] === 1'b1) ? tmp_70_fu_1813_p3 : tmp_67_fu_1797_p4);

assign tmp_77_fu_1156_p3 = p_Val2_i_fu_1149_p3[32'd41];

assign tmp_78_fu_1164_p1 = p_Val2_i_fu_1149_p3[21:0];

assign tmp_79_fu_1206_p1 = r_V_fu_1198_p3[1:0];

assign tmp_7_fu_876_p2 = ((indexstores_reg_420 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_80_fu_1218_p1 = p_Val2_i_fu_1149_p3[23:0];

assign tmp_81_fu_1348_p1 = P1Buf_V_0_1_P0Buf_V_s_fu_1341_p3[7:0];

assign tmp_82_fu_1352_p1 = ap_phi_reg_pp1_iter7_P0Buf_0_V_3_reg_471[7:0];

assign tmp_83_fu_1356_p1 = P1Buf_V_1_1_P0Buf_V_s_fu_1334_p3[7:0];

assign tmp_84_fu_1360_p1 = ap_phi_reg_pp1_iter7_P0Buf_1_V_3_reg_504[7:0];

assign tmp_85_fu_1603_p1 = tmp_90_cast_fu_1596_p1[9:0];

assign tmp_86_fu_1607_p1 = tmp_91_cast_fu_1599_p1[9:0];

assign tmp_87_fu_1617_p3 = p_Val2_3_fu_1611_p2[32'd23];

assign tmp_88_fu_1625_p2 = (tmp_86_fu_1607_p1 + tmp_85_fu_1603_p1);

assign tmp_89_fu_1683_p1 = tmp_90_1_cast_fu_1676_p1[9:0];

assign tmp_8_fu_846_p2 = (($signed(i3_reg_432) < $signed(loop_row_count_reg_2172)) ? 1'b1 : 1'b0);

assign tmp_90_1_cast_fu_1676_p1 = p_Val2_2_1_reg_2530;

assign tmp_90_2_cast_fu_1756_p1 = p_Val2_2_2_reg_2535;

assign tmp_90_cast_fu_1596_p1 = p_Val2_2_reg_2525;

assign tmp_90_fu_1687_p1 = tmp_91_1_cast_fu_1679_p1[9:0];

assign tmp_91_1_cast_fu_1679_p1 = p_Val2_13_1_fu_1669_p3;

assign tmp_91_2_cast_fu_1759_p1 = p_Val2_13_2_fu_1749_p3;

assign tmp_91_cast_fu_1599_p1 = p_Val2_s_27_fu_1589_p3;

assign tmp_91_fu_1697_p3 = p_Val2_14_1_fu_1691_p2[32'd23];

assign tmp_92_fu_1705_p2 = (tmp_90_fu_1687_p1 + tmp_89_fu_1683_p1);

assign tmp_93_fu_1763_p1 = tmp_90_2_cast_fu_1756_p1[9:0];

assign tmp_94_fu_1767_p1 = tmp_91_2_cast_fu_1759_p1[9:0];

assign tmp_95_fu_1777_p3 = p_Val2_14_2_fu_1771_p2[32'd23];

assign tmp_96_1_fu_1711_p2 = ((tmp_92_fu_1705_p2 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_96_2_fu_1791_p2 = ((tmp_96_fu_1785_p2 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_96_fu_1785_p2 = (tmp_94_fu_1767_p1 + tmp_93_fu_1763_p1);

assign tmp_9_fu_667_p2 = (($signed(j_cast_fu_663_p1) < $signed(imgInput_cols_read)) ? 1'b1 : 1'b0);

assign tmp_fu_621_p1 = imgOutput_cols_read[15:0];

assign tmp_i_fu_900_p1 = reg_572;

assign xnew_fu_612_p3 = {{imgInput_cols_read}, {28'd0}};

assign ynew_fu_626_p3 = {{imgInput_rows_read}, {28'd0}};

always @ (posedge ap_clk) begin
    xnew_reg_2068[27:0] <= 28'b0000000000000000000000000000;
    ynew_reg_2094[27:0] <= 28'b0000000000000000000000000000;
    scalex_V_reg_2104[0] <= 1'b0;
    scaley_V_reg_2109[0] <= 1'b0;
    bound_reg_2114[0] <= 1'b0;
    bound_reg_2114[33] <= 1'b0;
    tmp_51_i_reg_2187[42:25] <= 18'b000000000000000000;
    tmp_56_i_reg_2193[21:0] <= 22'b0000000000000000000000;
    tmp_59_i_reg_2198[21:0] <= 22'b0000000000000000000000;
    tmp_65_i_reg_2203[21:0] <= 22'b0000000000000000000000;
    indexx_pre_V_1_i_reg_2208[21:0] <= 22'b0000000000000000000000;
    lhs_V_6_reg_2440[8] <= 1'b0;
    rhs_V_4_reg_2450[8] <= 1'b0;
    lhs_V_6_1_reg_2470[8] <= 1'b0;
    rhs_V_4_1_reg_2480[8] <= 1'b0;
    lhs_V_6_2_reg_2500[8] <= 1'b0;
    rhs_V_4_2_reg_2510[8] <= 1'b0;
end

endmodule //resizeNNBilinear
